axodotdev/cargo-dist

- .github/workflows/release.yml
- cargo-dist-schema/src/lib.rs
- cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap
- cargo-dist/src/ci.rs
- cargo-dist/src/cli.rs
- cargo-dist/src/installer.rs
- cargo-dist/src/lib.rs
- cargo-dist/src/main.rs
- cargo-dist/tests/cli-tests.rs
- cargo-dist/tests/snapshots/cli_tests__long-help.snap
- cargo-dist/tests/snapshots/cli_tests__manifest.snap
- cargo-dist/tests/snapshots/cli_tests__short-help.snap
need to merge this to do some live runs on ci, will definitely break things for a bit
> progress on installer

- README.md
> provide manual instructions for releasing

- RELEASES.md
- cargo-dist-schema/cargo-dist-json-schema.json
- cargo-dist-schema/src/lib.rs
- cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap
- cargo-dist/Cargo.toml
- cargo-dist/src/lib.rs
- cargo-dist/tests/snapshots/cli_tests__manifest.snap
And use this to grab more static assets. More facts are computed than are used right now, I'm not 100% sure yet which fields we want to surface and on what level of abstraction, but whenever we *do* decide to do that they're ready to go
> Properly compute a bunch of facts about each package

- cargo-dist/src/main.rs
> tracing goes to stderr

- cargo-dist/src/ci.rs
> Set `ALL_CARGO_DIST_INSTALLER_ARGS` to `''`.

- cargo-dist/src/tasks.rs
- cargo-dist/tests/snapshots/cli_tests__manifest.snap
> disable pdb

- cargo-dist/src/ci.rs
> don't update rustup

- cargo-dist/src/tasks.rs
> try to use no-prerelease release notes if available

- Cargo.toml
- cargo-dist/src/lib.rs
> final default dist profile

- cargo-dist/src/tasks.rs
> add proper newlines after Release Notes

- RELEASES.md
- cargo-dist/src/ci.yml
- cargo-dist/src/main.rs
- cargo-dist/src/tasks.rs
- cargo-dist/tests/cli-tests.rs
- cargo-dist/tests/snapshots/cli_tests__error_manifest.snap
- cargo-dist/tests/snapshots/cli_tests__lib_manifest.snap
also includes a drive-by change to make --output-format=json also include human errors on stderr
fixes #130
> allow libraries to be singular-released minimally

- book/src/SUMMARY.md
- book/src/cargo-release-guide.md
- book/src/simple-guide.md
- book/src/way-too-quickstart.md
- book/src/workspace-guide.md
This was something folks were running into when trying it out over the weekend, because I punted on these docs. That got it in my craw and 5 hours later I have suddenly written the docs, so uh, here they are! I'll be taking off more time during the actual week to compensate :)
> add docs for using cargo-release

- Cargo.toml
- cargo-dist/src/lib.rs
- cargo-dist/src/main.rs
- cargo-dist/src/tasks.rs
- cargo-dist/tests/snapshots/cli_tests__manifest.snap
Currently semi-WIP, I need to actually dig out my macbook to test this lol
fixes #133
> Use rustup to install the appropriate macOS target when doing mac->mac crosses

- cargo-dist/src/installer.ps1
This does not implement actually building something other than X64.
This checks for architects that matches the current operating system's architecture. It falls back to X64 if none are available.
Related issue: #85
> PowerShell installer: use manifest to select files to download.

- .gitattributes
- .github/workflows/installers.yml
fixes #188 for now
i wanted to write these in rust with the command interface but ran into some trouble, so this should work *for now* and can revisit when @Gankra is back
> test(installers): add github action to run installers

- cargo-dist/src/ci.rs
> fix(yml): ensure all yml line-endings are LF

- cargo-dist/templates/ci.yml
> Remove Useless Uses of Cat

- cargo-dist/src/tasks.rs
* fix handling of metadata.dist: If metadata.dist = true was set it would inappropriately short-circuit all other checks and mark the package as distributable, even if the tag disagreed. fixes #187
* enforce config subsetting: If you pass --installer or --ci to the build/manifest/plan commands
they will now ignore any values that aren't a subset of the config in your Cargo.tomls, making the CLI more consistently a way to select subsets of the full build plan. fixes #158
> Config fixes

- .github/workflows/web.yml
- cargo-dist/oranda.json
I've commented out the "push" mode in this copy because I like transactions/control.
> update to more robust/explained oranda web.yml

- book/book.toml
i hate crlf issues i am so haunted why is this a thing
> convert newlines in book

- .github/workflows/ci.yml
- .github/workflows/web.yml
> update GitHub Actions CI

- .github/workflows/append-release.yml
- cargo-dist/src/cli.rs
- cargo-dist/src/main.rs
> chore: add command for dist-manifest-schema printing and upload it to releases

- cargo-dist/tests/gallery/dist.rs
- cargo-dist/tests/gallery/repo.rs
- cargo-dist/tests/integration-tests.rs
- cargo-dist/tests/snapshots/akaikatana_basic-installers.snap
This also reworks the gallery code to properly have a global lock between all Repos since we cd into the repo before running a test, which is global mutable state. I did this by requiring you to define a global lock for Tools that must be passed by-ref into each TestContextLock::new call, and using that as THE global lock (which is fine, Tools getting initialized once for each Repo was jank anyway).
> chore: add misty's project to the gallery

- cargo-dist/templates/ci/github_ci.yml.j2
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
> fix: add license line to generated ci.yml

- CHANGELOG.md
- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
I haven't published this as a tag yet, but prepping so we can test the new feature while working on followups.
> 0.2.0-prerelease.1

- Cargo.toml
- cargo-dist/tests/snapshots/manifest.snap
Let's enable the Homebrew installer for ourselves now that support has shipped.
> chore: enable Homebrew installer

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
> release: 0.2.0-prerelease.4

- book/src/config.md
- book/src/installers.md
Since this references tap publishing from #339, we should wait to merge this until that PR's in.
> docs: add Homebrew installer/config

- .github/workflows/release.yml
- cargo-dist/templates/ci/github_ci.yml.j2
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
> fix: minor typo in GitHub CI

- cargo-dist/src/cli.rs
- cargo-dist/tests/snapshots/long-help.snap
- cargo-dist/tests/snapshots/markdown-help.snap
> fix(cli): fix cut-off documentation

- book/src/installers.md
This field was added after these docs were written.
> docs(homebrew): mention publish-jobs

- .github/workflows/release.yml
- Cargo.toml
Updates to cargo-dist 0.2.0 and regenerates the CI config.
> chore(ci): update own cargo-dist

- book/book.toml
This makes it behave like common search engines
> make search less surprising

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
Making a prerelease with the current part of ci++ so we can more easily test it in our own CI.
> release: 0.3.0-prerelease.1

- book/src/config.md
- cargo-dist/src/errors.rs
This landed in the 0.3.0 prerelease, but didn't make the docs yet.
> docs(config): add allow-dirty

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
We should get #414 into a prerelease.
> release: 0.3.0-prerelease.3

- cargo-dist/src/lib.rs
The previous code accidentally assumed there was only one subscriber to each binary, and so if there were multiple ones one of them would arbitrarily win and get to copy the binary, while the other wouldn't silently get dropped.
The exact way it got dropped also bypassed the safety checks against this, alas.
The fix is simple: make the subscribers a list, instead of a single entry.
> fix: properly handle multiple subscribers to a binary

- cargo-dist/src/lib.rs
It's not that these files were *wrong* so much as this format is more useful.
> fix: generate properly formatted checksum files

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
Incorporates two new fix PRs from this afternoon.
> release: 0.3.0-prerelease.5

- cargo-dist/src/cli.rs
- cargo-dist/tests/snapshots/long-help.snap
- cargo-dist/tests/snapshots/markdown-help.snap
- cargo-dist/tests/snapshots/short-help.snap
> chore(cli): hide generate-ci command

- .github/workflows/append-release.yml
- .github/workflows/publish-release.yml
- cargo-dist/templates/ci/github_ci.yml.j2
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap
Fixes #440.
Build using this PR appears to be working just fine: https://github.com/mistydemeo/cargodisttest/actions/runs/6253405126
(The "bad credentials" thing is that the token I was using expired, not anything to do with this PR.)
> chore(ci): use checkout@v4

- CHANGELOG.md
- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
> release: 0.3.1

- cargo-dist/src/lib.rs
This ensures that we preserve the full name of a package, tap included, if it was installed from a non-default tap. We do this by reading Homebrew's install receipt for packages we detected as coming from Homebrew. If the receipt exists, we read it out and check what tap the package is from; if it's not `homebrew/core`, we then prepend it to the detected package name.
> feat(packages): get name of Homebrew tap if exists

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
- cargo-dist/tests/snapshots/error_manifest.snap
I thought it might be useful to get a prerelease out right away with package support.
> release: 0.4.0-prerelease.1

- .github/workflows/release.yml
- Cargo.toml
Updates us to the prerelease from #464.
> chore: update own cargo-dist

- CHANGELOG.md
0.4.0 isn't quite there yet, but I felt it'd be useful to get the changelog written up now with the features that are already in.
> docs(changelog): document 0.4.0 features

- cargo-dist/src/init.rs
> fix(init): correct link to Homebrew docs

- CHANGELOG.md
- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
A new prerelease that incorporates several major bugfixes and improvements to system dependencies and the linkage report.
> release: 0.4.0-prerelease.3

- Cargo.lock
- cargo-dist/Cargo.toml
- cargo-dist/src/announce.rs
- cargo-dist/src/errors.rs
This will eventually be a separate repo so that it's usable by other packages.
> feat: break tag parsing into crate

- cargo-dist/src/linkage.rs
From the new Rust release today.
> chore: satisfy clippy

- cargo-dist/src/generic_build.rs
This fixes an issue where stdout/stderr were being captured from the build and not piped through to the shell, making it harder to determine why it failed.
> fix: print stdout/stderr from generic builds

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
increases file upload timeouts
> chore: update gazenot to 0.1.1

- Cargo.lock
- cargo-dist/Cargo.toml
- cargo-dist/src/backend/installer/msi.rs
- cargo-dist/tests/snapshots/axolotlsay_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap
* Query the possible renders
* Diff them all
* Write them all
* Default to emitting license=false and eula=false to disable all the auto-eula stuff
> feat(eula): update cargo-wix and use new eula APIs for extra files

- cargo-dist-schema/src/lib.rs
- cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap
- cargo-dist/src/backend/ci/github.rs
- cargo-dist/src/config.rs
- cargo-dist/src/host.rs
- cargo-dist/src/init.rs
- cargo-dist/src/manifest.rs
- cargo-dist/src/tasks.rs
- cargo-dist/templates/ci/github_ci.yml.j2
- cargo-dist/tests/integration-tests.rs
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/akaikatana_musl.snap
- cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_musl.snap
- cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
This was always planned, I just punted on it for an MVP
> feat(axo-releases): change hosting to be an array

- cargo-dist/src/env.rs
This should be a runtime check.
> fix(env): bad reference to env!

- cargo-dist/src/tasks.rs
> fix: add missing doc field

- Cargo.lock
- Cargo.toml
- cargo-dist/Cargo.toml
- cargo-dist/tests/snapshots/error_manifest.snap
depends on https://github.com/axodotdev/axocli/pull/19
> chore: clean up some release process warts

- .github/workflows/append-release.yml
This needs to survive one more release before extra-artifacts are available.
> fix(ci): dependency name for append-release

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
Since we have a couple of new features, seems like a good time to start testing a prerelease.
> release: 0.6.0-prerelease.1

- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
Looks like these got missed when both the installer changes got merged at once.
> fix: tests for installer changes

- cargo-dist/src/tasks.rs
It's possible to run cargo-dist in something that's not a git repo; we should skip generating a tarball automatically in that case. I ran into this when creating a new test project, and noticed that `cargo build` was trying to run `git archive` even though it wasn't a git repo yet.
> fix: skip git tarball when necessary

- cargo-dist/src/generic_build.rs
Pipe stdout from the subprocesses directly to stderr.
> feat(generic): adjust stdout=>stderr redirect

- CHANGELOG.md
I've drafted up the changelog for the upcoming 0.6.0 documenting the current state of its new features and bugfixes.
> docs: draft changelog for 0.6.0

- CHANGELOG.md
- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
- rust-toolchain.toml
Prepping for the 0.6.0 release.
> release: 0.6.0

- cargo-dist/src/tasks.rs
We had an issue where we would still build extra artifacts even if they'd been filtered out of the target artifact list. This fixes that.
The issue was caused by the separate logic we had to use to add these builds to the graph. Because each of these builds produces multiple artifacts, we weren't able to add them in the same place that other global artifacts are added. However, that meant we weren't taking into account the list of target artifacts - we were unconditionally building them, even if we didn't want them.
Also fixes an issue where they were assigned to the local build array instead of the global build array, though the impact of that bug was minor.
Fixes #658.
> fix(extra artifacts): avoid inappropriate builds

- book/src/way-too-quickstart.md
Currently the image is duplicated from the section above.
> Fix image reference

- CHANGELOG.md
- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
I won't actually release this until the docs are ready.
> release: 0.7.0

- cargo-dist/src/tasks.rs
When deciding whether to generate a source tarball, we check whether the user is in a git repo but we don't check if that git repo has any commits. This is an edge case, but very possible: a user might have run `git init`, added some code, but not yet committed anything.
Fixes #695.
> fix(source): skip source tarballs if no commits

- cargo-dist/src/errors.rs
> Link to configuration reference in parsing error

- cargo-dist/templates/installer/homebrew.rb.j2
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
- cargo-dist/tests/snapshots/install_path_cargo_home.snap
- cargo-dist/tests/snapshots/install_path_env_no_subdir.snap
- cargo-dist/tests/snapshots/install_path_env_subdir.snap
- cargo-dist/tests/snapshots/install_path_env_subdir_space.snap
- cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap
- cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap
- cargo-dist/tests/snapshots/install_path_home_subdir_min.snap
- cargo-dist/tests/snapshots/install_path_home_subdir_space.snap
- cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
In my last PR I missed adding the bin install section that is OS/platform specific.
> Fix Linux Homebrew installation for binaries.

- CHANGELOG.md
- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
This does contain a new feature; do we want to make it 0.9.0?
> release: 0.8.2

- book/src/ci/customizing.md
> docs: fix mistyped links

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
Also updates us to the latest prerelease so we're building ourselves with what will be this release.
> release: 0.9.0

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
- cargo-dist/tests/snapshots/error_manifest.snap
- cargo-dist/tests/snapshots/lib_manifest.snap
- cargo-dist/tests/snapshots/lib_manifest_slash.snap
- cargo-dist/tests/snapshots/manifest.snap
> chore: update cargo-dist to 0.9.0

- book/src/reference/config.md
This was very, very old and was missing several available options.
> docs(config): update outdated target config

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
- cargo-dist/src/init.rs
Updates a number of our deps for the breaking miette change.
> chore: update deps

- cargo-dist/src/tasks.rs
These fallbacks are present for x86_64 musl, but not arm64.
> fix(installers): missing arm64 musl fallbacks

- book/src/installers/homebrew.md
- book/src/reference/config.md
- cargo-dist/src/config.rs
- cargo-dist/src/init.rs
- cargo-dist/src/tasks.rs
- cargo-dist/tests/gallery/dist.rs
- cargo-dist/tests/integration-tests.rs
- cargo-dist/tests/snapshots/axolotlsay_custom_formula.snap
> feat(formula): add config

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
Incorporates the updater for testing.
> release: 0.12.0-prerelease.1

- cargo-dist/templates/ci/github_ci.yml.j2
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/akaikatana_musl.snap
- cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
- cargo-dist/tests/snapshots/akaikatana_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
- cargo-dist/tests/snapshots/axolotlsay_custom_formula.snap
- cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap
- cargo-dist/tests/snapshots/axolotlsay_dispatch.snap
- cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss_only.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
- cargo-dist/tests/snapshots/axolotlsay_musl.snap
- cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_no_locals.snap
- cargo-dist/tests/snapshots/axolotlsay_no_locals_but_custom.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap
- cargo-dist/tests/snapshots/axolotlsay_tag_namespace.snap
- cargo-dist/tests/snapshots/axolotlsay_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
> chore: fix typo in GitHub CI template

- LICENSE-APACHE
- LICENSE-MIT
> chore: update license copyright year

- .github/workflows/ci.yml
> test: apply matrix OS as key to cache

- cargo-dist/templates/installer/installer.ps1.j2
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
- cargo-dist/tests/snapshots/akaikatana_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap
- cargo-dist/tests/snapshots/axolotlsay_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
- cargo-dist/tests/snapshots/install_path_cargo_home.snap
- cargo-dist/tests/snapshots/install_path_env_no_subdir.snap
- cargo-dist/tests/snapshots/install_path_env_subdir.snap
- cargo-dist/tests/snapshots/install_path_env_subdir_space.snap
- cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap
- cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap
- cargo-dist/tests/snapshots/install_path_home_subdir_min.snap
- cargo-dist/tests/snapshots/install_path_home_subdir_space.snap
- cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
This is essentially the same as #928, but adapted to powershell. Because of the simpler logic in this file, the changes are much smaller.
> fix: clean up for install (.ps1)

- Cargo.lock
- cargo-dist/Cargo.toml
Things brings us down to a single axoasset in-tree.
> chore: update axolibs

- CHANGELOG.md
- cargo-dist/templates/ci/github_ci.yml.j2
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/akaikatana_musl.snap
- cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
- cargo-dist/tests/snapshots/akaikatana_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
- cargo-dist/tests/snapshots/axolotlsay_custom_formula.snap
- cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap
- cargo-dist/tests/snapshots/axolotlsay_dispatch.snap
- cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss_only.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
- cargo-dist/tests/snapshots/axolotlsay_musl.snap
- cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_no_locals_but_custom.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap
- cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap
- cargo-dist/tests/snapshots/axolotlsay_tag_namespace.snap
- cargo-dist/tests/snapshots/axolotlsay_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
also some driveby yaml dependency fixes
> fix: force on windows longpaths for windows local builds

- cargo-dist/src/config.rs
- cargo-dist/templates/ci/github_ci.yml.j2
- cargo-dist/templates/ci/partials/publish_homebrew.yml.j2
- cargo-dist/templates/ci/partials/publish_npm.yml.j2
- cargo-dist/tests/integration-tests.rs
- cargo-dist/tests/snapshots/akaikatana_basic.snap
- cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
- cargo-dist/tests/snapshots/akaikatana_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
- cargo-dist/tests/snapshots/axolotlsay_custom_formula.snap
- cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
- cargo-dist/tests/snapshots/axolotlsay_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
```diff
2801 │+  publish-npm:
2802 │+    needs:
2803 │+      - plan
2804 │+      - host
2805 │+    runs-on: "ubuntu-20.04"
2806 │+    env:
2807 │+      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
2808 │+      PLAN: ${{ needs.plan.outputs.val }}
2809 │+    if: ${{ !fromJson(needs.plan.outputs.val).announcement_is_prerelease || fromJson(needs.plan.outputs.val).publish_prereleases }}
2810 │+    steps:
2811 │+      - uses: actions/setup-node@v4
2812 │+        with:
2813 │+          node-version: '20.x'
2814 │+          registry-url: 'https://registry.npmjs.org'
2815 │+      - run: |
2816 │+          for release in $(echo "$PLAN" | jq --compact-output '.releases[] | select([.artifacts[] | endswith("-npm-package.tar.gz")] | any)'); do
2817 │+            pkg=$(echo "$release" | jq '.artifacts[] | …
```
> build npm publish in

- book/src/reference/config.md
- cargo-dist/src/backend/ci/github.rs
- cargo-dist/src/config.rs
- cargo-dist/src/errors.rs
- cargo-dist/src/init.rs
- cargo-dist/src/tasks.rs
- cargo-dist/templates/ci/github_ci.yml.j2
- cargo-dist/tests/integration-tests.rs
- cargo-dist/tests/snapshots/axolotlsay_no_locals.snap
This lets you publish to a different repo than the builtin one
> feat: add github-releases-repo config

- book/src/reference/config.md
- cargo-dist/src/config.rs
- cargo-dist/src/init.rs
- cargo-dist/src/tasks.rs
- cargo-dist/tests/gallery/dist/npm.rs
- cargo-dist/tests/integration-tests.rs
- cargo-dist/tests/snapshots/axolotlsay_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap
- cargo-dist/tests/snapshots/axolotlsay_alias.snap
- cargo-dist/tests/snapshots/axolotlsay_alias_ignores_missing_bins.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
- cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
- cargo-dist/tests/snapshots/axolotlsay_musl.snap
- cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_several_aliases.snap
- cargo-dist/tests/snapshots/axolotlsay_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
> feat: add npm-package config

- cargo-dist/src/announce.rs
- cargo-dist/src/config.rs
- cargo-dist/src/tasks.rs
- rust-toolchain.toml
Includes updates from the new version of clippy.
> chore: update to rust 1.78

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
Incorporates the npm cache fix in #1050.
> release: 0.15.0-prerelease.15

- Cargo.lock
- cargo-dist-schema/Cargo.toml
- cargo-dist/Cargo.toml
We have a few new features in, so let's do a prerelease with them to expedite testing.
> release: 0.15.0-prerelease.20

- cargo-dist/src/backend/ci/github.rs
- cargo-dist/src/errors.rs
> feat: validate checksums when vendoring actions

- book/src/reference/config.md
- cargo-dist/src/config.rs
> fix: Add `.tar.zst` suffix for Zstd

- CHANGELOG.md
- book/src/reference/config.md
- cargo-dist/src/backend/ci/github.rs
- cargo-dist/src/config.rs
- cargo-dist/src/errors.rs
- cargo-dist/src/init.rs
- cargo-dist/src/tasks.rs
- cargo-dist/templates/ci/github/release.yml.j2
We're reconsidering the requirements for this at the moment.
> chore: back out vendor-deps

- CHANGELOG.md
This adds the missing 0.15.0 items to the changelog.
> docs: 0.15.0 changelog

- cargo-dist/src/build/generic.rs
- cargo-dist/src/config.rs
- cargo-dist/src/init.rs
- cargo-dist/src/lib.rs
- cargo-dist/src/tasks.rs
> fix: rework extra_artifacts to properly use paths

- cargo-dist/src/config.rs
Previously, it was possible for axoproject to reach outside the root of the current repository and find things in the parent repository. This caused problems for our tests, where we might find multiple workspaces and end up preferring cargo-dist itself over the repo we're trying to run tests on.
> feat: clamp workspace search to root of current repo

- .github/workflows/publish-crates.yml
This I believe requires a change to the token used to publish
> chore: add axoproject to autopublishes

- cargo-dist/src/backend/installer/homebrew.rs
> fix: wrong comment for homebrew

- book/src/reference/config.md
Refs https://github.com/axodotdev/cargo-dist/issues/179#issuecomment-2245245647.
> docs: correct min version for libraries

- book/src/reference/config.md
Changes to the final name we decided on.
> docs: update staticlib name

- Cargo.lock
- Cargo.toml
Ensures this release is still reflected in our commit history on main.
> Backport release to main

- cargo-dist/src/init.rs
Now that we support generic workspaces that include Cargo members, some users may prefer having their cargo-dist config in a cargo-dist-specific format instead of hitching a ride in Cargo.toml. This provides an option to migrate configuration.
At the start of init, check if we read config from Cargo.toml and offer to use dist-workspace.toml. If the user says yes, and we already had configuration in Cargo.toml, finish off the init process by deleting the old content from Cargo.toml.
> feat: allow init to migrate config

- cargo-dist/src/init.rs
This fixes a couple of problems which led to two issues in first-time init projects - we'd try to put `[dist]` in the wrong file, and we'd produce a wrong `dist-workspace.toml` if that was fixed.
* We still need to generate the root workspace in dist-workspace.toml even if we have no `[dist]` to copy into it.
* We need to ensure we override the filename in the !initted case.
> fix: init for first-time projects

- cargo-dist/src/init.rs
* don't try to be clever and just default github ci on
* don't ask about pr-run-mode
The first one lets us ram face first into a better error about repository URLs after saving all your settings. The second one is just it being noise to ask and not helpful.
> feat: simplify first init

- Cargo.lock
- Cargo.toml
Incorporates several more init fixes.
> release: 0.20.0-prerelease.8

- book/src/reference/config.md
duplicate section, style tweak
> doc: fixups

- README.md
> docs(readme): update links for new docs

- README.md
We don't want the noun/verb "setup" here.
> Grammatical clarification README.md

- cargo-dist/src/init.rs
Addresses https://github.com/axodotdev/cargo-dist/issues/1275
> reverse homebrew logic if user unchecks it

- axoproject/src/errors.rs
- axoproject/src/generic.rs
- cargo-dist/src/build/generic.rs
- cargo-dist/src/config.rs
- cargo-dist/src/errors.rs
- cargo-dist/src/init.rs
- cargo-dist/src/tasks.rs
* fixes #1332
* fixes #1336 
* fixes #1338 
Also does a general "don't say generic to users" pass
> fix: random error/prompt cleanups

- book/src/quickstart/everyone-else.md
- book/src/quickstart/javascript.md
- book/src/quickstart/rust.md
- book/src/workspaces/simple-guide.md
Minor correction in instructions
> Use singular quotes, alternatively we should escape the !

- cargo-dist/src/announce.rs
While I don't use it yet, I thought it would be useful to make the return value of this function an enum that's actually actionable rather than just a human-legible string.
> feat: make disabled reason actionable

- .github/workflows/release.yml
- cargo-dist/Cargo.toml
- cargo-dist/tests/snapshots/manifest.snap
- dist-workspace.toml
I'd like to start testing this in dist itself.
Extracted from #1267 for clarity.
> feat: enable npm installer

- cargo-dist-schema/src/lib.rs
- cargo-dist/src/backend/ci/github.rs
- cargo-dist/src/config/v0.rs
- cargo-dist/src/config/v1/ci/github.rs
Follow-up to #1474, done while working on #1470
> Make `GithubRunner` strongly typed

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
This contains the changelog for this release. This branch needs to be rebased after all changes for the release are in before we actually tag it.
> release: 0.24.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- axoproject/src/rust.rs
This is a minor point release that incorporates #1501.
This was branched from the v0.24.0 tag to avoid bringing in a few minor changes that were merged since the 0.24.0 release.
> release: 0.24.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Draft until the full contents are merged.
> release: 0.25.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> release: 0.25.1

- book/src/reference/config.md
- book/src/supplychain-security/index.md
I'd apparently set this aside with `git stash` and forgot to commit it with #1528. :sweat:
> Add cargo-auditable docs.

- cargo-dist/src/main.rs
This is part of a broader goal of permitting `dist plan` to run in a `dist` workspace with multiple packages which are independently versioned. Today, `dist plan` fails (and thus `dist`'s GitHub Actions on PRs fail) in such a workspace because it can't resolve a coherent tag.
Under the hood, `dist plan`'s `cmd_plan` function delegates to `cmd_manifest` after configuring some settings, and `cmd_manifest` itself further configures the system to demand tag coherency.
This commit splits out the body of `cmd_manifest` into a new `generate_manifest` function, which is equivalent to `cmd_manifest` except it accepts a new `needs_coherence` parameter (so named to match the `Cli::tag_settings` method's parameter name). With this new function introduced, `cmd_manifest` is updated to call …
> feat: Permit tag incoherence for `dist plan`

- cargo-dist/src/main.rs
This only affects the "human" output.
Output for an "incoherent" plan with multiple different versions:
Output for a "coherent" plan with only one version:
> Improve interactive `dist plan` output if there's multiple versions in a workspace

- Cargo.toml
> fix: real msrv is 1.74

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
We're not quite ready to tag this - we have a few action items before then.
> release: 0.26.0

- cargo-dist/src/backend/ci/github.rs
- cargo-dist/src/tasks.rs
- cargo-dist/tests/integration-tests.rs
- cargo-dist/tests/snapshots/axolotlsay_cross2.snap
Cross-compiling from Windows to Windows using zigbuild is broken; we're getting `zig cc` errors we can't fix. We should always use xwin instead. If we detect Windows cross-compilation, we should always pick an xwin container image, specifically the same one we recommend our users to use.
Sample broken build: https://github.com/mistydemeo/cargodisttest/actions/runs/12305247980/job/34344574841#step:9:46
```
error: linking with `C:\Users\runneradmin\AppData\Local\cargo-zigbuild\0.19.5\zigcc-aarch64-pc-windows-msvc-b7f1.bat` failed: exit code: 1
|
= note: "cmd" "/c" "C:\\Users\\runneradmin\\AppData\\Local\\cargo-zigbuild\\0.19.5\\zigcc-aarch64-pc-windows-msvc-b7f1.bat" "/NOLOGO" "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\rustct8HDn7\\symbols.o" …
```
> fix: always cross-compile to windows via xwin

- CHANGELOG.md
> Update changelog for 0.27.1

- .github/workflows/release.yml
- dist-workspace.toml
> chore: update own dist

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Incorporates #1658.
~~This remains a draft until #1647 is merged, so we can ship that in this release.~~ Done.
> release: 0.28.0

- Cargo.lock
- Cargo.toml
- cargo-dist/tests/gallery/dist/snapshot.rs
This release contains the rename but no other content. Any remaining 1.0 content will come after the first prerelease.
> release: 1.0.0-rc.1

- book/src/installers/powershell.md
Follow up to #1658
The powershell docs were technically wrong before, because they seemed to imply that only a shell restart was required, when really you had to restart your whole machine. Luckily that means that updating the docs to reflect the current state of the world was easy, because now you really do only need the shell restart 😄
> Update docs related to #1658

- CHANGELOG.md
Brings the changelog from #1843 into the main branch.
> release: 0.28.1-prerelease.1

- .github/workflows/release.yml
- cargo-dist/tests/snapshots/lib_manifest.snap
- cargo-dist/tests/snapshots/lib_manifest_slash.snap
- cargo-dist/tests/snapshots/manifest.snap
- dist-workspace.toml
Also reverts the temporary build commit changes that were done so we could build from 0.28.0.
> Update to 0.28.1-prerelease.1

- cargo-dist/templates/installer/npm/npm-shrinkwrap.json
- cargo-dist/templates/installer/npm/package.json
- cargo-dist/tests/snapshots/axolotlsay_abyss.snap
- cargo-dist/tests/snapshots/axolotlsay_alias.snap
- cargo-dist/tests/snapshots/axolotlsay_alias_ignores_missing_bins.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
- cargo-dist/tests/snapshots/axolotlsay_build_setup_steps.snap
- cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
- cargo-dist/tests/snapshots/axolotlsay_musl.snap
- cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_several_aliases.snap
- cargo-dist/tests/snapshots/axolotlsay_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
Backports two dependabot commits from main:
db8d0583a87c577274a4c9565a32498168d6be23
6872bdd64308c1a168555e47417597b214975746
> Update npm deps

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
One final prerelease; this contains the npm dependency upgrades.
> release: 0.28.1-prerelease.5

- .github/workflows/web.yml
I missed this reference when changing the other bit of config.
> docs: fix stable branch docs publishing

- Cargo.lock
- Cargo.toml
Forgot to cut the previous prerelease using 0.28.2-pre1, so one last prerelease for the road.
> release: 0.28.2-prerelease.3

- cargo-dist/src/backend/ci/github.rs
- cargo-dist/src/config/v0.rs
- cargo-dist/src/config/v0_to_v1.rs
- cargo-dist/src/config/v1/ci/github.rs
- cargo-dist/src/init.rs
- cargo-dist/templates/ci/github/release.yml.j2
- cargo-dist/tests/integration-tests.rs
- cargo-dist/tests/snapshots/axolotlsay_action_commit.snap
Merged from https://github.com/astral-sh/cargo-dist/pull/16.
Refs #1839.
> feat: add github-action-commits config

- cargo-dist/src/backend/ci/github.rs
- cargo-dist/templates/ci/github/partials/publish_github.yml.j2
- cargo-dist/templates/ci/github/partials/publish_homebrew.yml.j2
- cargo-dist/templates/ci/github/partials/publish_npm.yml.j2
- cargo-dist/tests/snapshots/axolotlsay_action_commit.snap
These were missed in the upstream PR and in #1944; I've pulled them in here to keep them from landing in unrelated commits.
> fix: missing action action-commits config

- axoproject/src/generic.rs
- axoproject/src/javascript.rs
- axoproject/src/lib.rs
- axoproject/src/rust.rs
- cargo-dist/src/announce.rs
- cargo-dist/src/tests/mock.rs
Merged from https://github.com/astral-sh/cargo-dist/pull/30.
Refs #1839.
> feat: add packages override for externally setting dist=true/false

- axoproject/src/generic.rs
Merged from https://github.com/astral-sh/cargo-dist/pull/31.
Refs #1839.
> feat: add workspace.version override

- cargo-dist/src/config/v0.rs
- cargo-dist/src/config/v0_to_v1.rs
- cargo-dist/src/config/v1/artifacts/mod.rs
- cargo-dist/src/init.rs
- cargo-dist/src/lib.rs
- cargo-dist/src/tasks.rs
Merged from https://github.com/astral-sh/cargo-dist/pull/41 / https://github.com/astral-sh/cargo-dist/pull/43.
Refs #1839.
> feat: add recursive-tarballs

- Cargo.lock
- Cargo.toml
Contains the new features from Astral's fork, but no documentation yet.
> release: 0.29.0-prerelease.1

- CHANGELOG.md
Brings in the last few releases from the other branch.
> docs: update changelogs

- cargo-dist/src/sign/macos.rs
Backports #1743 to the 0.x branch.
> Support --options in mac code signing

- devenv.nix
#2009 cherry-picked to the stable branch.
> chore: add devenv.nix

- cargo-dist/templates/installer/npm/binary-install.js
- cargo-dist/tests/snapshots/axolotlsay_action_commit.snap
- cargo-dist/tests/snapshots/axolotlsay_alias.snap
- cargo-dist/tests/snapshots/axolotlsay_alias_ignores_missing_bins.snap
- cargo-dist/tests/snapshots/axolotlsay_attestations_filters.snap
- cargo-dist/tests/snapshots/axolotlsay_attestations_host.snap
- cargo-dist/tests/snapshots/axolotlsay_basic.snap
- cargo-dist/tests/snapshots/axolotlsay_basic_bins.snap
- cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
- cargo-dist/tests/snapshots/axolotlsay_build_setup_steps.snap
- cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap
- cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
- cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
- cargo-dist/tests/snapshots/axolotlsay_musl.snap
- cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap
- cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
- cargo-dist/tests/snapshots/axolotlsay_several_aliases.snap
- cargo-dist/tests/snapshots/axolotlsay_updaters.snap
- cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
- cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
Backports #2046 to the 0.x branch.
> fix: platform.includes bug (#2046)

- cargo-dist/tests/gallery/dist/homebrew.rs
Homebrew removed the ability to install a formula from a path on disk in 4.6.4: https://github.com/Homebrew/brew/releases/tag/4.6.4 But there's a specific carveout for if these two environment variables are set. We're just using this for tests too, so use them.
> tests: fix homebrew runtests

- CHANGELOG.md
> docs: changelog for version 0.30.0
