axodotdev/cargo-dist

cargo-dist/src/ci.rs
Here's a tiny nitpick: changing the ™ symbol used in the GitHub CI script 😀
™ (U+2122) is the non-Emoji version of ™️ (U+2122 U+FE0F) and should render better, especially in dark-mode etc.
```
™️
trademark sign
Unicode: U+2122 U+FE0F, UTF-8: E2 84 A2 EF B8 8F
™
TRADE MARK SIGN
Unicode: U+2122, UTF-8: E2 84 A2
```
**For example in [Boop](https://github.com/IvanMathy/Boop):**
=> Replace ™️ with ™ (for aesthetic reasons)

cargo-dist-schema/src/lib.rs
Currently, this is writing the schema file without first truncating. That means if this writes fewer bytes than currently exist in the file, whatever extra bytes were at the end of the file remain. Thiss is probably not a valid JSON file.
You can reproduce the problem by doing roughly:
```bash
cargo test
echo test >> cargo-dist-schema/cargo-dist-json-schema.json
cargo test
```
Expected: the file is overwritten with the new schema.
Actual: the file still contains the extra "test" at the end.
=> Fix writing of cargo-dist-json-schema.json

cargo-dist/src/installer.ps1, cargo-dist/src/installer.rs
This makes it easier to test changes to the script. Instead of running cargo-dist to regenerate the script, you can pass command line arguments to the script that is checked into the Git repo.
The reason behind this change is to make it easier to work on #85.
To make sure the script still works after these changes, I ran these commands that download the current v0.0.2 release:
```batch
cargo run -- dist --no-builds --installer=github-powershell
powershell target\distrib\installer.ps1
```
Here is an example using command line arguments in a PowerShell prompt to test the script:
```powershell
.\installer.ps1 -repo https://github.com/axodotdev/cargo-dist -app_name cargo-dist -package_version v0.0.2
```
=> Store PowerShell installer in a standalone file

RELEASES.md, cargo-dist/src/tasks.rs
Fixes #142 by appending the prerelease suffix to sugar'd release titles.
An example: if you try to create a release for `1.0.0-pre1` and we detect a changelog entry of the form `## v1.0.0` the title of the release notes will end up as "v1.0.0-pre1".
Another example: you try `3.0.0-prerelease5`, we detect `## Version 3.0.0 (not yet released!)`, the title will end up "Version 3.0.0-prerelease5 (not yet released!)"
I am unsure whether we would want to strip the "(not yet released!)" part as well. When looking at the GitHub releases page they seem kinda confusing - a released version that says it is not released :exploding_head:
The problem is that it is not clear how we should detect such an indication. A simple solution would be to just strip everything after the first opening parenthesis. …
=> Append prerelease suffix to sugar'd release titles

cargo-dist-schema/cargo-dist-json-schema.json, cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/src/lib.rs, cargo-dist/src/main.rs, cargo-dist/tests/snapshots/cli_tests__manifest.snap
fixes #150 
Note that there's currently a weird denormalization where an artifact is referenced by id, but also has a "name" which is just the id again, but Optional. This is intentionally left in as future space for #72.
=> Dist manifest cleanup

book/book.toml
Show 2 new icons:
- github repository
- button to edit the current page in GitHub 
You might also want to add the [site-url](https://rust-lang.github.io/mdBook/format/configuration/renderers.html?highlight=site-url#html-renderer-options) option to improve the 404 links.
It should be something like this:
```
site-url = "/cargo-dist/book/"
```
=> chore(book): show repository link

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/main.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/snapshots/cli_tests__error_manifest.snap, cargo-dist/tests/snapshots/cli_tests__long-help.snap, cargo-dist/tests/snapshots/cli_tests__markdown-help.snap, cargo-dist/tests/snapshots/cli_tests__short-help.snap
as expected, axocli works perfectly for cargo-dist and obsoletes most of `main.rs`.
I'm not sure I'm in love with the current interface for axoproject though, especially since cargo-dist has the *easy* case compared to oranda
=> update deps and use axocli

cargo-dist/templates/ci.yml, cargo-dist/templates/installer.sh, cargo-dist/templates/npm/binary.js
Some of the files that `cargo dist` generates (namely, the GitHub release workflow and the installer scripts) contain lines with trailing spaces, which violates numerous coding standards.  This PR gets rid of the trailing whitespace in these files.
Note that there are many other files in this repository with lines with trailing spaces (I would recommend using [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) via [pre-commit](https://github.com/pre-commit/pre-commit) to get rid of trailing whitespace and keep it out), but I have opted to leave them alone for the purposes of this PR.
=> Remove trailing spaces from templated files

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/errors.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs
This turns `cargo dist init` into an interactive setup/updater that walks you through setting things up (recommended settings can all be selected by mashing ENTER over and over). Including:
* prompting you to update your project to the version of cargo-dist you're running (refuses to proceed otherwise)
* prompting you to select what CI backend to use (only one option, github)
* enabled by default if we see your project's repo contains "github"
* errors out if you don't have a consistently set repository url in your workspace's Cargo.tomls
* prompting you to select what installers to enable
* skips if no CI backend is enabled, as we use this to derive fetch URLs for artifacts
* if npm is enabled:
* if newly enabled, prompts you to provide an `@scope`
* if tar.gz artifacts aren't enabled, …
=> usable interactive init/update?

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/installer.rs, cargo-dist/src/tasks.rs
Closes #220. I hope I caught all the necessary places keywords needed to be shoehorned in? It looks right to me.
=> feat: support keywords in npm installer

cargo-dist/templates/npm/binary.js, cargo-dist/templates/npm/install.js
Without this change, the argument passed from `run.js` is ignored:
https://github.com/axodotdev/cargo-dist/blob/4daf3da315032d73c2dcc263412d55c27cc1525d/cargo-dist/templates/npm/run.js#L4
FYI, `suppressLog` is a partially inverted in `binary-install` package: https://github.com/EverlastingBugstopper/binary-install/pull/23, but it is still better to pass `true` to avoid "... is already installed, skipping installation." message being printed on every CLI run.
=> fix(npm-installer): Update binary.js to respect suppressLog passed from run.js

cargo-dist/oranda.json, cargo-dist/oranda/cargo-dist.css
actual ci script unchanged because the republish has the same url
=> update to latest oranda

cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs
npm expects this dir to exist and implicitly 'strips' it when searching for things like READMEs
fixes #238
=> generate npm tarballs with 'package' as the dir name

Cargo.lock, book/src/config.md, cargo-dist-schema/cargo-dist-json-schema.json, cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/Cargo.toml, cargo-dist/oranda.json, cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/main.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/snapshots/cli_tests__manifest.snap
We now default generate .sha256 checksum files (one for each archive). Example:
A new `checksum = "..."` config has been added, accepting 3 values:
* "sha256" (default)
* "sha512"
* "false" (disable checksumming)
All checksums are implemented with the sha2 crate and match sha256sum and sha512sum's hashes. The resulting file is just a lowercase hex string of the hash (no filename included, since each file gets its own .sha256 file). I've defaulted to sha256 since that seems to be the default other people use, and if you're really serious about hardening this stuff you probably want actual signing/pki backing this up (like #120).
I've also cleaned up the Github Release table output a bit as part of this.
=> add basic support for shasums 

cargo-dist/templates/ci.yml
This makes us behave properly for project with git submodules, at no cost to projects that don't need it(?)
fixes #242
=> recursively checkout submodules in ci template

CHANGELOG.md, cargo-dist/src/tasks.rs
parse_changelog supports a special section title of 'Unreleased', which we can default to if we're publishing a prerelease and fail to find any entry for it.
Fixes #145
=> Fallback to the  Unreleased section in changelogs

book/src/config.md, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs
Setting it to true tells us to Build only the required packages, and individually (default: false)
By default when we need to build anything in your workspace, we build your entire workspace with --workspace. This setting tells cargo-dist to instead build each app individually.
On balance, the Rust experts we've consulted with find building with --workspace to be a safer/better default, as it provides some of the benefits of a more manual [workspace-hack][], without the user needing to be aware that this is a thing.
TL;DR: cargo prefers building one copy of each dependency in a build, so if two apps in your workspace depend on e.g. serde with different features, building with --workspace, will build serde once with the features unioned together. However if you build each package …
=> feat(precise-builds): add a precise-builds config and default it false

book/src/config.md, cargo-dist/src/ci.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci.yml
[feat(fault-isolate): add merge-tasks config and default it to false](https://github.com/axodotdev/cargo-dist/commit/10f740b24f22094f49858ce98b4d9e76d6c9fbe8)
This config specifies whether we should try to merge otherwise-parallelizable tasks onto the same machine, sacrificing latency and fault-isolation for more the sake of minor effeciency gains.
For example, if you build for x64 macos and arm64 macos, by default we will generate ci which builds those independently on separate logical machines. With this enabled we will build both of those platforms together on the same machine, making it take twice as long as any other build and making it impossible for only one of them to succeed.
The default is false. Before 0.1.0 it was always true and couldn't be changed, making releases annoyingly …
=> feat(fault-isolate): prefer independent tasks and don't fail-fast

Cargo.lock, book/src/config.md, cargo-dist/Cargo.toml, cargo-dist/src/cli.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/main.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/snapshots/cli_tests__markdown-help.snap
This exists for hosted services that want to edit the toml mechanically.
The format is basically the json equivalent of `[workspace.metadata.dist]`,
wrapped in a `workspace` field:
```json
{
"workspace": {
"cargo-dist-version": "0.1.0-prerelease.2",
"ci": ["github"],
"installers": ["shell", "powershell"],
"targets": ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc", "aarch64-apple-darwin"]
}
}
```
The given values will complete overwrite the `[workspace.metadata.dist]` section,
so if any fields are omitted they will be deleted from the Cargo.toml.
All the interactive logic that `init` supports will be ignored in this mode
(this is *NOT* equivalent to --yes, which runs the logic and just accepts every prompt).
generate-ci will be run afterwards as usual (disable …
=> feat(json-init): add a --with-json-config=path/to/config.json flag for passing json to init

cargo-dist/templates/installer.ps1.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/cli_tests__long-help.snap, cargo-dist/tests/snapshots/integration_tests__basic-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_cargo_home-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_env_no_subdir-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_env_subdir-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_env_subdir_space-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_env_subdir_space_deeper-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_home_subdir_deeper-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_home_subdir_min-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_home_subdir_space-installers.snap, cargo-dist/tests/snapshots/integration_tests__install_path_home_subdir_space_deeper-installers.snap
* fetches axolotolsay (can be configured to any repo)
* applies an overlay to the Cargo.toml
* runs cargo dist build -aglobal on it (builds installer scripts)
* runs shellcheck on the shell scripts (if available)
* runs PSScriptAnalyzer on the powershell scripts (if available)
* insta snapshots both scripts
The OVERRIDE_CARGO_BIN_EXE_cargo-dist variable also lets you inject a different binary for cargo-dist, which will let us run these tests for shippable binaries (infra not yet implemented)
=> chore: introduce integration tests for installers

cargo-dist/templates/installer/installer.ps1.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
* PSScriptAnalyzer hates Write-Host, says use Write-Information
* Write-Information is actually silent by default
* Write-Host is an alias for Write-Information -InformationAction Continue
* You can set the InformationPreference var in your script to set the the default InformationAction value
So I guess this is the idiomatic way to print information messages?
=> fix: make ps1 print statements visible

book/src/config.md, cargo-dist/src/config.rs, cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs
This adds the following configs to metadata.dist:
```toml
features = ["blah", "blargh"]
default-features = false
all-features = true
```
If applied to [workspace.metadata.dist] it will be applied to all packages
If applied to [package.metadata.dist] it will be applied to just that package (overriding the workspace value if it exists).
If not all packages end up with the same feature flags then precise-builds=true will be forced on.
fixes #274
=> feat(features): add the ability to specify features

cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap
This looks like a possible typo; it was introduced in #297. Fixes a parse error I ran into when `cargo init`ing from a fresh repo using this prerelease version.
=> fix(ci): fix a typo in rustup update

cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
shellcheck rule SC2317:
https://www.shellcheck.net/wiki/SC2317
This was introduced in shellcheck 0.9.0 which explains why it wasn't seen in CI because it uses shellcheck 0.8.0 (because that's what's packaged in Ubuntu 22.04).
Fixes #344 (issue also has some more shellcheck details)
Incidentally this PR also includes some whitespace cleanup that my editor decided to perform. Let me know if that is undesired and I'll revert those!
Also, I'm not sure what `assertion_line` is or why it was removed in the updated insta snapshots?
=> fix: unreachable code in installer.sh template

cargo-dist/templates/installer/homebrew.rb.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
A real-world test indicated that Homebrew is reliably misparsing the version from the URLs. Instead of letting Homebrew guess, let's just be explicit.
=> fix(homebrew): add explicit version tag

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/config.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
It's legal for a repository URL to end with .git, but cargo-dist currently assumes it's a web URL rather than a git clone URL before working with it. This makes sure we strip the .git part of the URL before tacking on the `/release` path so we generate a valid URL.
I considered putting this in `axoproject` but it felt wrong to be messing with the repository URL from `Cargo.toml` over there.
Fixes #263.
=> fix: strip .git from repo URL before appending

cargo-dist/src/backend/templates.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
Alternate to #354 - append trailing a trailing newline if the rendered template doesn't have one. minijinja always strips trailing newlines; this is likely easier than always remembering to add an extra newline to templates.
Closes #354.
=> fix(templates): append trailing newline if needed

.github/workflows/release.yml, Cargo.toml, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/manifest.snap
This newer version will let us test pushing to our Homebrew tap.
=> chore: update CI to latest cargo-dist

cargo-dist/src/init.rs
The Homebrew messages were associated with the wrong side of the if statement.
=> fix(init): Homebrew messages were incorrect

Cargo.toml, cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
This is a quick spike of the new `publish_jobs` config field. Now, instead of just using `tap` to decide whether to enable a Homebrew publish job, we also have this new field. Right now, we don't explicitly ask the user to enable it and instead implicitly enable it if `tap` is enabled, but we can update the `init` UI for that if we want.
=> feat: add publish_jobs config field

book/src/config.md, cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
=> feat: add create-release config to allow people to draft their own releases

.github/workflows/release.yml, Cargo.toml
I actually just did this to test the Homebrew-installed binary, but we might as well bump to run the next build on prerelease 5.
=> chore: update own cargo-dist

book/src/cargo-release-guide.md, book/src/concepts.md, book/src/install.md, book/src/introduction.md, book/src/way-too-quickstart.md, book/src/workspace-guide.md, cargo-dist/src/cli.rs, cargo-dist/src/errors.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/mock.rs, cargo-dist/src/tests/mod.rs, cargo-dist/src/tests/tag.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/cli-tests.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/lib_manifest_slash.snap, cargo-dist/tests/snapshots/long-help.snap, cargo-dist/tests/snapshots/markdown-help.snap
Allows usage in repos that use a slash to separate the crate name from the version.
Examples:
- `myapp/v1.0.0`
- `myapp-thing/v1.2.3`
Resolves #343
I built it locally and tested on a repo of mine, and it seems to work as expected (before it would just fail of course, due to the unsupported tag format):
First prepping a release with `cargo-release`:
```
❯ cargo release minor -x       
Release
facti-lib 0.3.0
facti-api 0.3.0
facti 0.3.0
? [y/N] 
y
Upgrading facti-lib from 0.2.1 to 0.3.0
Updating facti's dependency from 0.2.1 to 0.3.0
Updating facti-api's dependency from 0.2.1 to 0.3.0
[feature/cargo-dist-slash 479058c] Release facti-lib v0.3.0
5 files changed, 8 insertions(+), 5 deletions(-)
Upgrading facti-api from 0.2.0 to 0.3.0
Updating facti's dependency from 0.2.0 to 0.3.0 …
```
=> feat: support slash as tag separator

cargo-dist/src/config.rs
I accidentally left this one string as a `TODO` in the ci++ PR.
=> fix(config): add missing docstring for pr_run_mode

cargo-dist-schema/src/lib.rs, cargo-dist/src/backend/ci/github.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap, cargo-dist/tests/snapshots/lib_manifest.snap, cargo-dist/tests/snapshots/lib_manifest_slash.snap, cargo-dist/tests/snapshots/manifest.snap
* make plan the default (as originally agreed?)
* make the init code actually remember what you had set before
* make the init code not write a value if it's the default
* make the init code produce compile errors if a new PrRunMode is added
* rework the prompt order/messages to be clearer
=> feat(ci): cleanup default/init logic for pr_run_mode

book/src/install.md
This doesn't actually work with the dist profile in the workspace `Cargo.toml`.
Fixes #399.
=> docs(install): remove --profile=dist

book/src/config.md, cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap, cargo-dist/tests/snapshots/lib_manifest.snap, cargo-dist/tests/snapshots/lib_manifest_slash.snap, cargo-dist/tests/snapshots/manifest.snap
We currently unconditionally publish prereleases to package managers. We should instead disable that by default while optionally enabling it.
I've left it out of `init` because I see this as more of a power user feature; I've documented it but don't think we should prompt most users about it.
Fixes #398.
=> feat(ci): allow disabling publishing prereleases

cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/snapshots/error_manifest.snap, cargo-dist/tests/snapshots/lib_manifest.snap, cargo-dist/tests/snapshots/lib_manifest_slash.snap, cargo-dist/tests/snapshots/manifest.snap
Fixes an issue where the preflight config check would use whichever artifact options the user had passed. If --artifacts=local was passed, we would be inappropriately flagging GitHub CI as out of date because we'd try to omit the global artifacts.
=> fix(check): analysis uses --artifacts=all

.gitignore, CHANGELOG.md, Cargo.lock, book/src/concepts.md, cargo-dist/Cargo.toml, cargo-dist/src/backend/installer/mod.rs, cargo-dist/src/backend/installer/msi.rs, cargo-dist/src/cli.rs, cargo-dist/src/config.rs, cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/main.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/gallery/dist.rs, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/long-help.snap, cargo-dist/tests/snapshots/markdown-help.snap, cargo-dist/tests/snapshots/short-help.snap
The "msi" installer vendors the binaries into a windows msi.
msi generation is implemented by using cargo-wix as a library,
which in turn handles generating templates and invoking WiX (v3).
The resulting msi's are unsigned -- signing will be handled by a followup,
as changes to OV certs mean that "proper" signing is now very complicated
and messy.
This implementation has some notable details:
main.wxs generation
--------------------
WiX requires an xml-based template called main.wxs for each msi it generates.
This template includes things like the application name, version, publisher,
EULA, embedded files, and so on.
cargo-wix's default workflow is for you to run `cargo wix init` once to generate
that file and check it in. At this point the developer is free to hand-edit
the template to …
=> feat(msi): add msi installer

cargo-dist/src/backend/installer/msi.rs
it writes to stdout which messes up --output-format=json
=> fix: don't forward WiX output

.github/workflows/release.yml, Cargo.toml
Uses the new prerelease just shipped in #412, and removes the temporary workaround introduced in `Cargo.toml`.
=> chore(ci): update own cargo dist

Cargo.lock, cargo-dist/Cargo.toml
This release cuts down our dependency tree substantially.
=> chore: axoasset 0.5.1

.github/workflows/release.yml, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/main.rs
* new target selection UI
* if you have Github CI enabled, we won't ask anymore
* if you have pr-run-mode set, we won't ask anymore (we also no longer omit it from output when the default is selected, so that we can distinguish new init from made-a-decision)
* extra unimportant words removed
* if you have no CI backend enabled we will still allow you to turn on msi
* we will always run generate at the end (unless --no-generate-ci is set) because generate now detects which parts need to run on its own (and the current logic was preventing CI-less MSI from working).
* `[profile]` de-emphasized, sent to the end, not mentioned if unchanged
=> feat(init): various fixes/improvements

Cargo.lock, cargo-dist/Cargo.toml
fixes unstable cargo-metadata ordering
=> chore: update cargo-wix to 0.3.7

.gitignore
This ensures that `oranda dev` doesn't generate untracked changes visible to `git status`.
=> chore: add oranda to .gitignore

book/src/SUMMARY.md, book/src/customizing-ci.md
This begins a new section in the documentation with the new features from CI++, including PR release builds and custom publish jobs.
I felt that there's enough detail here it's worth a new section in the docs, in particular as we start extending it with new features and CI backends other than GitHub.
Although these are tagged with the appropriate version, we should still avoid merging this until closer to feature availability.
=> docs: document new CI features

cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config.rs, cargo-dist/src/errors.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
This adds support for user-defined jobs in CI. Currently, we support publish jobs specifically, and these run parallel with other publish jobs. These are specified in TOML via the `user_publish_jobs` hash:
```toml
user_publish_jobs = { github = ["./.github/workflows/something.yml"] }
```
Fixes #379.
=> feat(ci): add support for user-defined jobs

cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
As far as I can tell, the "parse out" lines were the only parts that actually depended on bash semantics.
Fixes #460.
cc @frol
=> fix(ci): Windows builds should not run under bash

cargo-dist-schema/README.md
Fix link to the book. The linked target did not exist anymore. The used markdown  was not correctly rendered on crates.io.
Screenshot of the previous state:
I adapted the target to a site that exists. Because the schema is not described (anymore?) in the book I also updated the link text.
=> chore(docs): Fix link in cargo-dist-schema readme

cargo-dist/src/lib.rs
Add missing backtick in doc comment of cargo_dist::GenerateArgs.
Previous rendering on docs.rs:
Rendering on my PC with the proposed change:
=> chore(docs): Fix formating in cargo_dist::GenerateArgs doc comment

cargo-dist/src/init.rs, cargo-dist/src/lib.rs
The new clippy included with Rust 1.73.0 flags some more things in our `main` branch. We need this to make CI green again.
=> chore: update with latest clippy fixes

cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/src/backend/ci/github.rs, cargo-dist/src/backend/installer/homebrew.rs, cargo-dist/src/errors.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap, cargo-dist/tests/snapshots/manifest.snap
As planned in #426 and #428, this leverages the linkage reporter to detect which packages to add as dependencies to the Homebrew formula. Even if the user doesn't specify them as runtime dependencies, if we saw that a Homebrew package was dynamically linked against, we'll add it to the list of dependencies.
This requires us to store linkage data between runs so we can fetch it later. We do that by storing the dist metadata after each build in the temporary artifact bucket, and then download it at the time we build the Homebrew formula in order to gain access to linkage data for every build.
For a sample of how this was used, I tested with a package which specified two Mac dependencies:
```toml
[workspace.metadata.dist.dependencies.homebrew]
cmake = { targets = ["x86_64-apple-darwin"] } …
```
=> feat(homebrew): use linkage to infer deps

cargo-dist/src/backend/installer/homebrew.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs
This is a followup to #475. In that PR, I enabled reusing previous dist manifests from previous builds in a CI environment. It doesn't, however, cover the case where the previous builds happened within the *same run*. This fixes that. I've split local/global builds into separate categories from each other, instead of just by ordering them within a single array. I then added a temporary computation of dist manifests after local builds are run, but before global builds are run; that temporary manifest is then passed to any global job that cares to ask for it. Currently, it's only consumed by the Homebrew installer, but it might be wanted by something else later.
=> feat(installers): pass data from local builds to global

book/src/ci/github.md
This adds some documentation for our new auto-detected dependency feature, and mentions that it's also possible to specify it manually. I tired to avoid going into technical detail as to how it works to avoid overloading users with detail.
=> docs(deps): Describe auto-detected deps

cargo-dist/src/lib.rs
We don't currently have a supported path that produces these, but musl builds will encounter it. Rather than try to parse a file like this, if we see this message we can immediately return from the `ldd` parser.
=> fix(linkage): handle static executables

cargo-dist/src/backend/ci/github.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap
This adds support for musl builds on Linux. This currently supports x86_64 but not aarch64, as with glibc. Sample successful build: https://github.com/mistydemeo/cargodisttest/actions/runs/6540051759/job/17759406467 A few notes:
* We're building on an Ubuntu host, so it's not being built on a musl-native distro.
* We use the official, default Rust tooling for this from `rustup`, which means musl is statically linked instead of dynamically linked like some musl-based distros prefer.
* Because of this, *dynamically linking to external dependencies will fail* in musl builds. I briefly toyed with disallowing system dependency installation for that reason, but there's no reason to block people from installing cmake/whatever build tools just because they won't be able to link against some …
=> feat(build): enable Linux musl builds

cargo-dist/src/backend/installer/homebrew.rs
This fixes the one empty string that was being produced per manifest file being read.
Fixes #485.
=> fix(homebrew): correct map for inferred linkage

CHANGELOG.md, Cargo.lock, cargo-dist-schema/Cargo.toml, cargo-dist/Cargo.toml
This incorporates the static musl builds. We probably want to wait to release this until #486 and #485 are addressed.
=> release: 0.4.0-prerelease.2

cargo-dist/src/tasks.rs, cargo-dist/templates/installer/installer.sh.j2, cargo-dist/templates/installer/npm/binary.js.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl_no_gnu.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
Now that we have musl binaries, we should teach the installers to use them. In particular, we want to ensure musl gets used in the following circumstances:
* The user is running a non-glibc-based distro, in which case the glibc binaries are guaranteed not to run
* The user is running a glibc-based distro, but their glibc is too old to run the glibc binaries we built
This makes the following changes:
* `install.sh` uses musl
* npm uses musl
* npm inherits the macOS Rosetta code that it was missing
=> Installers: add musl detection

cargo-dist/src/lib.rs
The path linked against might be a symlink that `dpkg -S` can't resolve to the providing package. If we do a `realpath` call on it, we get a path that we can more reliably resolve later.
=> fix(linkage): improve apt package resolution

cargo-dist/src/errors.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/mock.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
Replaces #499; I broke my git tree badly enough GitHub doesn't want to let me reopen it.
=> feat(deps): pick and choose parts of brew bundle exec

cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs
This is a very simplistic flag because in the future we need to do some more principled/complex design work for dynamic vs static libc, and its relationship to system dependencies and installers.
For now it's basically an escape hatch for people who want to roll the dice.
=> feat(msvc-crt-static): add msvc-crt-static config for changing the default

cargo-dist/src/lib.rs
We've seen a minor UI issue with Linux dependencies. I anticipated catching the error status output from `dpkg -S` and reacting to that, but we were still getting cases where not finding the package and accidentally returning an empty string as the "package". This checks for that case and properly handles it.
Before this fix, the linkage reporter was giving us outputs like:
```
/path/to/lib ()
```
And with this fix, it looks like:
```
/path/to/lib
```
=> fix(sysdeps): handle empty Linux packages

Cargo.lock
We didn't do this the last couple releases, so it's a good time to update. Summary:
```
Updating crates.io index
Updating base64 v0.21.4 -> v0.21.5
Updating bitflags v2.4.0 -> v2.4.1
Updating clap v4.4.6 -> v4.4.7
Updating clap_builder v4.4.6 -> v4.4.7
Updating clap_derive v4.4.2 -> v4.4.7
Updating clap_lex v0.5.1 -> v0.6.0
Updating comfy-table v7.0.1 -> v7.1.0
Updating cpufeatures v0.2.9 -> v0.2.11
Updating crossterm v0.26.1 -> v0.27.0
Updating deranged v0.3.8 -> v0.3.9
Updating flate2 v1.0.27 -> v1.0.28
Updating futures-channel v0.3.28 -> v0.3.29
Updating futures-core v0.3.28 -> v0.3.29
Removing futures-macro v0.3.28
Updating futures-sink v0.3.28 -> v0.3.29
Updating futures-task v0.3.28 -> v0.3.29
Updating futures-util v0.3.28 -> v0.3.29
Updating hashbrown v0.14.1 -> v0.14.2
Updating …
```
=> chore(deps): cargo update

book/src/ci/github.md
Documents in more detail the current state of sysdeps on aarch64-apple-darwin.
While ideally we could provide a way to genuinely install all tools the user wants for the build target, we don't currently have the ability to do so.
Closes #498.
=> docs(sysdeps): clarify aarch64-apple-darwin situation

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/backend/installer/msi.rs, cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/gallery/dist.rs
We didn't actually use this crate, we just referenced a type from it. Now that axoproject reexports it, we can simply use its version instead of directly specifying it in Cargo.toml.
Draft until we have a new axoproject release.
Closes #534.
=> chore: replace guppy with axoproject's reference

cargo-dist/src/cargo_build.rs, cargo-dist/src/tasks.rs
This is an `Option`, we shouldn't `unwrap()` in case it's actually missing.
I added an `expect()` to the version since that field's actually mandatory, but it seems like we can cope with the package ID being missing.
=> fix(config): handle missing PackageId

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/backend/installer/homebrew.rs, cargo-dist/src/tasks.rs
We previously depended on an external crate, but its implementation wasn't 100% identical to Homebrew's. This replaces that with a custom function that implements Homebrew's logic precisely, along with a test case that covers all of Homebrew's test cases plus the two recently reported bugs.
Fixes #541.
Fixes #551.
=> fix(homebrew): reimplement Homebrew class code

CHANGELOG.md
This was in #556, which was a backport release feature btanch, so we never actually merged it.
fixes #562
=> Add release notes for v0.4.3

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/announce.rs, cargo-dist/src/cargo_build.rs, cargo-dist/src/config.rs, cargo-dist/src/env.rs, cargo-dist/src/errors.rs, cargo-dist/src/generic_build.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/mock.rs
This PR adds a new "generic" build type. Most of the process is identical to Cargo builds, but I've extended our build logic to add a new `GenericBuildStep` that encapsulates a large part of the different behaviour.
This is an MVP, and it's missing some features we likely want to see in the future:
* Only workspaces are supported; we don't have a concept of packages yet. Since we don't inherit anything like that from Cargo, we'll have to think about what this looks like.
* The user has to manually specify all of the binaries that the build output will contain, since we don't have Cargo to get that information from. In the future, we probably want to make these globs instead of literal paths so that we can accommodate more complex builds.
We defer most of the project loading and parsing …
=> feat: enable generic builds

cargo-dist/src/announce.rs
This new call to cargo() was missed when rebasing the generic builds branch on top of main pre-merge.
Fixes `cargo dist build` in generic repos.
=> fix: semver() over cargo()

cargo-dist/src/generic_build.rs
This adapts some logic from cargo builds to ensure we don't try to build targets unnecessarily, for example during a global build.
=> fix: ensure builds are skipped when appropriate

Cargo.lock, cargo-dist-schema/Cargo.toml, cargo-dist/Cargo.toml
makes uploads serial as a temporary fix to overloading connections
=> chore: update gazenot to 0.1.2

book/src/SUMMARY.md, book/src/generic-builds.md
This is the start of our generic build documentation. While this covers all of the essential configuration, we may want the surrounding text to be more substantive. We also want to decide what this feature is actually called, because "generic builds" is probably not the best name.
=> docs(generic): begin generic build docs

Cargo.lock, cargo-dist-schema/Cargo.toml, cargo-dist/Cargo.toml
gets backoff/retry semantics and proper concurrency limits
=> chore: update gazenot to 0.1.3

Cargo.lock, cargo-dist-schema/Cargo.toml, cargo-dist-schema/src/lib.rs, cargo-dist/Cargo.toml, cargo-dist/src/announce.rs, cargo-dist/src/host.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/mock.rs, cargo-dist/src/tests/tag.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/lib_manifest.snap, cargo-dist/tests/snapshots/lib_manifest_slash.snap
Kind of a grab-bag:
* rename tasks to match the conceptual model now that it's real
* should-publish => host
* announce-release/publish-release => announce
* clean up comments, add another test
* create an empty Release for a library-release, allowing everything to know it should be hosted/published/announced
* in theory this means library-releases to axo hosting should Now Work, but, not yet tested
* github Releases now get the pretty Release urls from axo hosting
* when performing `host --steps=release` we will update the artifact download urls with the result
* only the axodotdev url will be updated, if github hosting also is enabled it will still refer to the github release
* but we prefer the axodotdev url in multi-host-drifting so that's mostly academic
* we also will …
=> feat: cleanup github releases / ci contents

cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/src/errors.rs, cargo-dist/src/lib.rs, cargo-dist/src/manifest.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/gallery/repo.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap, cargo-dist/tests/snapshots/manifest.snap
This adds a new global artifact kind: source tarballs. This ensures that a stable tarball gets added to releases, wherever those are hosted. They're generated using `git archive`, so they're semantically equivalent to GitHub's auto-generated tarballs (but not byte-for-byte identical).
Do we want to be able to turn this off, or always have it on?
~~The tests are currently failing because we don't actually have access to the appropriate git tags to run the archives. I should probably try to get us to skip the source for that.~~ Fixed by updating the tests to fetch tags.
=> feat: add source tarballs

cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap
The broken test in question was added between the PR's last update and now, so it wasn't accounted for during the merge.
=> fix(tests): update for Linuxbrew

cargo-dist/src/generic_build.rs
Currently, we don't set `CC` or `CXX` when running generic builds. This is fine most of the time, but for makefile builds we probably want to hint at the makefile which platform-specific compiler should be used.
This respects `CC` and `CXX` from the external environment if set.
=> feat: set CC/CXX in generic builds

cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
We already use curl's `--fail` to try to propagate failure status, but the non-zero exit gets wiped away by the pipe. The shell only sees the last process in the chain's exit status, and since `sh` receives an empty string - which is a valid `sh` script - it treats it as a success.
I was going to explicitly `set -eo pipefail`, but turns out that explicitly marking the shell as `bash` gets you that; the shell configuration is different between the inferred shell and an explicit `bash` shell. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
Fixes #593.
=> fix(ci): fail fast if installer is missing

.gitignore, Cargo.toml, cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/src/cli.rs, cargo-dist/src/config.rs, cargo-dist/src/generic_build.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/main.rs, cargo-dist/src/manifest.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/snapshots/manifest.snap
This adds support for specifying arbitrary extra artifacts alongside the primary builds. These artifacts are currently expected to be architecture-independent and are uploaded as their own build artifacts rather than bundled into release tarballs. For example, we can use this to replace our current `append-release` code in to generate and upload the `dist-manifest-schema.json`.
I realized that most of our generic build code is very well-suited to this, so I split the existing generic builds into half. The code that runs the builds is now shared between this and the generic build path, while another section is separate for implementation detail reasons. There are two main distinctions between these and generic builds:
* Generic builds are oriented around *binaries*, which will eventually …
=> feat: extra build artifacts

cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/gallery/dist.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
~/.profile isn't sourced in many circumstances; we need to write this to a large number of locations to make sure it gets considered by bash and zsh under the largest number of circumstances.
Fixes #547.
=> feat(installer): add additional shell config

cargo-dist/src/init.rs
After experimenting with some changes here, I think I've concluded we don't want this in `init`. Otherwise, our `toml_edit` code will reformat it into the less pretty syntax:
```toml
github-custom-runners = { aarch64-unknown-linux-gnu = "buildjet-16vcpu-ubuntu-2204-arm" }
```
instead of
```toml
[workspace.metadata.dist.github-custom-runners]
aarch64-unknown-linux-gnu = "buildjet-16vcpu-ubuntu-2204-arm"
```
=> chore: remove stubbed init code

cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
Fixes #624
Previously, there would be benign broken pipe error due to the interaction between `ldd` and `head`. Now that error is no more.
=> Fix ldd broken pipe error

Cargo.lock, cargo-dist-schema/Cargo.toml, cargo-dist/Cargo.toml
This has no substantive changes from the previous prerelease, but will allow us to test append-release on cargo-dist itself.
=> release: 0.6.0-prerelease.2

cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
This fixes a UI regression from #555. After that PR, we now print the "source `.env`" message once *per rcfile we've edited*, rather than once overall. This updates it to print it only once, and only if at least one rcfile was edited.
=> fix(installer): only print source once

cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
This avoids a message about `ZDOTDIR` being unset when checking it.
=> fix: handle unset ZDOTDIR better

cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
This enables custom CI steps to be inserted into the CI process. These steps run alongside one of the following existing CI tasks:
* plan
* build-local-artifacts
* build-global-artifacts
* host (fka should-publish)
Additional publish-time jobs were already supported.
Implementation note: I expose these to the GitHub CI tooling as strings, but they're parsed from `Config.toml` as a new `JobStyle` enum. Right now the only type of `JobStyle` is `User`, which just wraps a string; I went for this both as an analogue to how we handle publish jobs, and so that we can automatically strip `./` on the way in and add it back on the way out - again like we do with publish jobs. This also gives us freedom to add new builtin jobs to each of these arrays in the future.
=> feat(ci): custom steps for other phases

cargo-dist/src/errors.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/mock.rs
This follows up #647 by also ensuring we don't call `git` if it's not present on the system. If it's missing, we skip trying to generate a source tarball altogether.
=> fix: check for git presence before calling

cargo-dist/templates/installer/installer.ps1.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
I don't know if this is correct, and I can't test myself, but this is my interpretation of the proposed fix in #484.
Fixes #484.
=> fix(powershell): replace errors with throw

book/src/reference/config.md
Adds documentation for `extra-artifacts`. Should be merged after #613; do we want to wait to add this to the docs until we get close to an 0.6.0?
=> docs: document extra artifacts

Cargo.lock, cargo-dist/Cargo.toml
Updates axoasset, ensuring that we get consistent behaviour with liblzma across all targets.
=> chore: update axoasset

Cargo.lock
`cargo publish` notified me that our version of self_cell was yanked.
=> chore(deps): update self_cell

cargo-dist/src/host.rs, cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
We were just uploading the global one, making us drop all local artifacts
(they still got *uploaded*, they just weren't in the dist-manifest).
Github Releases were still getting the right manifest because the Right
manifest would get written to disk immediately after uploading to Axo Releases.
=> fix: properly upload the "final" dist-manifest to axo releases 

cargo-dist/src/linkage.rs
This may fix the issue in CI where stdout from earlier in the process is awkwardly merged with the linkage's stderr.
=> fix(linkage): flush stdout/stderr before printing

cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github_ci.yml.j2
These jobs will be run after the "announce" step is run, ensuring that the GitHub release has been created already.
=> feat(ci): post-announce jobs

.github/workflows/publish-release.yml, .github/workflows/release.yml, Cargo.toml
This switches us to using custom hooks in order to publish to crates.io as a part of the normal release process instead of as a manual job.
=> chore(ci): replace crates.io publish with custom job

book/src/SUMMARY.md, book/src/ci/customizing.md, book/src/ci/github.md, book/src/ci/index.md, book/src/reference/config.md
This adds the new custom jobs to our existing documentation, with explanations of where each job runs.
=> docs(ci): document custom jobs

rust-toolchain.toml
Released 2023-12-28.
We can probably eventually remove this file; we need it for now because our minimum Rust is 1.74 and CI picked something older without hinting.
=> chore(toolchain): update to 1.75

cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
We accidentally measured these from a newer Ubuntu than we build on.
=> fix(shell installer): correct glibc version

cargo-dist/templates/installer/npm/binary.js.j2, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
we did this for shell but forgot about npm
=> fix: improve glibc bounds to npm installer

cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_no_locals.snap, cargo-dist/tests/snapshots/axolotlsay_no_locals_but_custom.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
We were using 'is from a fork' as a proxy for 'should have the secret' but evidently dependabot can make branches on your repo and trigger PR CI that doesn't have secrets. This regresses our ability to do validation that you've set things up right but it's more reliable.
=> fix: more literally disable host --check

cargo-dist/src/cli.rs, cargo-dist/src/config.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/cli-tests.rs, cargo-dist/tests/snapshots/markdown-help.snap
`--artifacts=lies` is equivalent to `--artifacts=all` except instead of being "something doomed to fail with `cargo dist build`" it just lies through its teeth and fakes the builds to generate all the files needed to upload.
This would let us have a staging upload workflow you can run on anyone's machine:
```
STAGE_INTO_THE_ABYSS=1
AXO_RELEASES_STAGING_TOKEN="...."
cargo dist host --steps=create
cargo dist build --artifacts=lies
cargo dist host --steps=upload --steps=release --steps=announce
```
=> feat(lies): add --artifacts=lies

cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_no_locals.snap, cargo-dist/tests/snapshots/axolotlsay_no_locals_but_custom.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
Migrates us from v3 to v4, with a refactor that has us using multiple artifact buckets instead of a single staging bucket.
This *doesn't* migrate the signing job yet. This one is awkward since the old behaviour actually did rely on overwriting a specific artifact. Do we have only one Windows target triple at the moment, or is there more than one that's possible? If there's only one, I can hardcode what we fetch and write to.
Sample build: https://github.com/mistydemeo/cargodisttest/actions/runs/7729932089
Sample release: https://github.com/mistydemeo/cargodisttest/releases/tag/v0.2.92
Fixes #653
=> feat(github): migrate to artifacts-v4

book/src/ci/customizing.md, book/src/reference/config.md
This has been available for a few months, but it looks like we never ended up documenting it.
=> docs(github): document custom runners

Cargo.lock, cargo-dist-schema/Cargo.toml, cargo-dist/Cargo.toml
Cutting a new prerelease following the latest batch of default runner changes to ensure our own release is made using these and not the prior choice.
=> release: 0.9.0-prerelease.3

.github/workflows/ci.yml
This should be much faster than `macos-latest`, which is currently `macos-12`.
=> ci: test on macos-14

cargo-dist/templates/installer/installer.ps1.j2, cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/gallery/dist.rs, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
=> chore: add tests for install-receipts from sh

cargo-dist/src/cli.rs, cargo-dist/tests/snapshots/markdown-help.snap
Makes most vecs args accept also --arg=A,B
=> chore: be more permissive in vec args

cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_no_locals.snap, cargo-dist/tests/snapshots/axolotlsay_no_locals_but_custom.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_tag_namespace.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
I managed to miss the other place this gets called.
=> fix(ci): add shell to other install location

cargo-dist/src/cargo_build.rs
On GitHub actions, adding that target seems to take a about 2 seconds. It's about the same amount of time whether or not the target was already installed.
=> Always invoke "rustup target add" when crosscompiling

cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/akaikatana_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
Going back to the earliest commits, this was always present in the requirements but `which` was never actually used even in the earliest commit. Presumably it was already removed before the first commit that introduced the installers.
Fixes #828.
=> fix: installer.sh doesn't require `which`

cargo-dist/templates/installer/installer.ps1.j2, cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/akaikatana_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
This provides a way to override any configuration on the installer and install to a location specified by a new environment variable. It provides a more predictable way to insist that it gets installed to a specific place, regardless of how the installer was built.
Possible fix for axodotdev/axoupdater#32, where we'd like to be able to install a new version to exactly the same path as the previous version.
=> feat: allow overriding install path

cargo-dist/src/backend/ci/github.rs, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
This ensures that homebrew/cask dependencies are specified appropriately in the generated Brewfile.
Fixes #850.
=> feat: support cask deps for Homebrew

cargo-dist/templates/installer/installer.ps1.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/akaikatana_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap, cargo-dist/tests/snapshots/install_path_cargo_home.snap, cargo-dist/tests/snapshots/install_path_env_no_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space.snap, cargo-dist/tests/snapshots/install_path_env_subdir_space_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_deeper.snap, cargo-dist/tests/snapshots/install_path_home_subdir_min.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space.snap, cargo-dist/tests/snapshots/install_path_home_subdir_space_deeper.snap
Fixes #834.
Right now, if `platforms` doesn't contain an entry for ARM64, `Download` falls back to x64, but `Invoke-Install` is missing matching fallback behavior, leading to failure.
=> Enable fallback to x64 in Invoke-Installer

cargo-dist/src/backend/ci/github.rs, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/manifest.snap
Not doing this was an oversight. There shouldn't be any harm to it.
Fixes #876.
=> fix: run apt-get update before install

Cargo.lock, cargo-dist/Cargo.toml
This release contains the fix for ZIP generation on Windows.
refs #873.
refs https://github.com/axodotdev/axoasset/pull/94
=> chore: bump axoasset to 0.9.1

CHANGELOG.md
These releases aren't part of the `main` branch since they were branched off of the `v0.12.0` tag instead of `main`; this brings in the changelog updates from them.
=> chore: port over changelogs from 0.12.1/2

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/cli.rs, cargo-dist/src/errors.rs, cargo-dist/src/main.rs, cargo-dist/tests/cli-tests.rs, cargo-dist/tests/snapshots/long-help.snap, cargo-dist/tests/snapshots/markdown-help.snap, cargo-dist/tests/snapshots/short-help.snap
An alternative to #896; this provides a `cargo dist update` command using axoupdater's lib. It also, optionally (and by default) runs `cargo dist update` from the new release after performing a successful upgrade, as suggested in #897.
=> Self update command

book/src/generic-builds.md
This is a tiny fix for a documentation link.
Update a [main quickstart documentation](https://opensource.axo.dev/book/way-too-quickstart.html) link which does't seem to work in [Generic Builds](https://opensource.axo.dev/cargo-dist/book/generic-builds.html#quickstart) page.
Thank you.
=> docs: fix invalid link in generic-builds page

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/tests/cli-tests.rs
This uses a new helper introduced in axoupdater in place of implementing it itself.
=> chore: break out selfupdate test via helpers

cargo-dist/templates/ci/github_ci.yml.j2, cargo-dist/tests/snapshots/akaikatana_basic.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap, cargo-dist/tests/snapshots/akaikatana_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap, cargo-dist/tests/snapshots/axolotlsay_custom_formula.snap, cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_tag_namespace.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
This will increase the size of the cache but should ensure more consistent cache hits, improving build times.
We tested this with our own CI builds and it does seem to work!
Fixes #907.
=> feat: CI - add key to cache call

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/main.rs, cargo-dist/tests/cli-tests.rs
This tests our own generated installers instead of the installers that were build for the version we're fetching. It asks axoupdater what version it plans to update to, then generates new installers and updates the version we're fetching to that instead of whatever cargo-dist would have generated. Using a new testing feature from axoupdater, we then substitute these new installers for the ones it would have downloaded from the new release.
=> feat: test building installers in updates

cargo-dist/src/errors.rs, cargo-dist/src/main.rs
These were missed with the switch to `cargo dist selfupdate`.
=> fix: cargo dist update messages

book/src/reference/config.md, cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap
Currently, source code tarballs are mandatory unless `git` happens to be missing from the system. This adds a new configure switch which allows turning it off.
=> feat: allow disabling source tarballs

.github/workflows/ci.yml, Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/main.rs
This should improve our flaky tests by using a token with a higher set of requests instead of unauthorized requests. Our tests have a pretty artificial environment where we perform a large number of requests in a very short amount of time, unlike real-world environments, so these rate limits weren't representative of real-world usage.
Requires https://github.com/axodotdev/axoupdater/pull/98.
=> tests: use github token for updater

Cargo.lock, cargo-dist/src/backend/installer/msi.rs, cargo-dist/src/config.rs, cargo-dist/src/init.rs
The toml_edit::Document type [moved to DocumentMut in 0.22.7](https://github.com/toml-rs/toml/blob/48f968b449d64a3b7bcefab37c3f08438ba857ec/crates/toml_edit/CHANGELOG.md?plain=1#L31).
I noticed that certain from-source git builds of cargo-dist were pulling in the newer toml_edit, so I figured it was worth it to update the locked version and switch to the new type.
=> chore: update toml_edit, type alias

book/src/reference/config.md, cargo-dist/src/config.rs, cargo-dist/templates/ci/github/release.yml.j2, cargo-dist/tests/snapshots/axolotlsay_no_locals.snap
and clarify behaviour in docs.
=> fix: use non-reserved SECRET name for github-releases-repo

cargo-dist/templates/installer/npm/npm-shrinkwrap.json, cargo-dist/templates/installer/npm/package.json, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_alias.snap, cargo-dist/tests/snapshots/axolotlsay_alias_ignores_missing_bins.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap, cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_several_aliases.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
Same as dependabot's PR, but with snapshots regenerated.
Closes #1010.
=> chore: update npm tar

book/src/reference/config.md, cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config.rs, cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github/release.yml.j2, cargo-dist/tests/snapshots/axolotlsay_no_locals.snap
This is the companion to [`github-releases-repo`](https://opensource.axo.dev/cargo-dist/book/reference/config.html#github-releases-repo); when targeting creating a commit in an external repo, where that repo is also checked out as a submodule of the repository in which the release is being run, this lets you consult the latest commit of that submodule and use that commit as the tag instead of whatever happens to be the latest commit in that repository.
=> feat: allow specifying external commit from submodule

cargo-dist/templates/installer/npm/binary-install.js, cargo-dist/templates/installer/npm/binary.js, cargo-dist/templates/installer/npm/run.js.j2, cargo-dist/tests/gallery/dist/npm.rs, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_alias.snap, cargo-dist/tests/snapshots/axolotlsay_alias_ignores_missing_bins.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap, cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_several_aliases.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
* this.binaryPath no longer exists, which was causing us to refetch every time
* Package.run already calls Package.install as a subroutine, there's no need to call it again and duplicate the work (potentially we could also remove that, but hey integrity checks are nice?)
* The additional logic in run to select a binary to call was an artifact of development, and never actually ran (trivially provable by nothing ever omitting the argument) (this logic is performed by npx itself because we populated package.json's 'bins')
=> fix: repair and cleanup npm binary caching

book/src/installers/npm.md
As far as I can tell, this isn't necessary. I was able to publish a package to `@mistydemeo/cargodisttest` without it being an organization.
=> docs: remove a line from npm docs

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/errors.rs, cargo-dist/src/lib.rs
Instead of querying releases and using that to see if an asset is available for our architecture, just manually construct the URL and use a HEAD request to see if it exists or not.
This should improve reliability when checking for new updater releases as a part of the local build process.
=> feat: fetch updater without GitHub API call

Cargo.lock, cargo-dist/Cargo.toml
I'd completely forgotten that enabling rustls doesn't do anything if you don't also `default-features - false`.
=> fix: really avoid native-tls

cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github/release.yml.j2
This adds a new feature which allows vendoring actions used within GitHub Actions run. I don't expect the majority of users to want this feature, but some security-conscious users may want it in order to ensure their CI runs use known versions of actions instead of arbitrary versions from floating tags.
This implementation works by cloning the actions' repositories into a `.github/actions` repository within the user's git repo. These are intended to be committed as files within the user's git repo and aren't treated as submodules. We'd previously experimented with a take where we instead vendored the repos within cargo-dist itself and wrote them like we do with our templates; however, this bloated the executable to an unnacceptable degree.
Note that "checkout" is the one action we can't …
=> feat: vendor GitHub actions

cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/src/build/mod.rs, cargo-dist/src/linkage.rs, cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
This makes it easier to track which package manager a package comes from for non-Homebrew packages, which could be located in multiple places. I've also added a new method to get a flat list of package name strings from the linkage data.
=> feat: add package manager source to library

Cargo.lock, cargo-dist/Cargo.toml
These are bundled together to make sure we can get reqwest updated at the same time we bump axoasset. Checking `Cargo.lock`, it did bring us down to a single revision of reqwest in the tree.
=> chore: axoasset 0.9.5/reqwest 0.12.4

Cargo.lock, cargo-dist/Cargo.toml, cargo-dist/src/sign/ssldotcom.rs
The workaround isn't necessary anymore now that axoasset 0.10.0 incorporates a [proper fix](https://github.com/axodotdev/axoasset/pull/126).
Drafted until axoasset 0.10.0 is cut.
=> fix: migrate to proper axoasset remote copy

cargo-dist/tests/gallery/dist/tools.rs, rust-toolchain.toml
Might be safe for us to actually remove the rust-toolchain version now. We had it because we have a minimum Rust version that not all of our runners were shipping by default yet, but that's probably no longer a concern.
=> chore: rust 1.79.0

axoproject/src/generic.rs, axoproject/src/javascript.rs, axoproject/src/lib.rs, axoproject/src/rust.rs, axoproject/src/tests.rs, axoproject/tests/projects/generic-workspace/CHANGELOG.md, axoproject/tests/projects/generic-workspace/LICENSE.txt, axoproject/tests/projects/generic-workspace/README.md, axoproject/tests/projects/generic-workspace/dist-workspace.toml, axoproject/tests/projects/generic-workspace/generic1/CHANGELOG.md, axoproject/tests/projects/generic-workspace/generic1/LICENSE.txt, axoproject/tests/projects/generic-workspace/generic1/Makefile, axoproject/tests/projects/generic-workspace/generic1/README.md, axoproject/tests/projects/generic-workspace/generic1/dist.toml, axoproject/tests/projects/generic-workspace/generic1/main.c, axoproject/tests/projects/generic-workspace/generic2/Makefile, axoproject/tests/projects/generic-workspace/generic2/dist.toml, axoproject/tests/projects/generic-workspace/generic2/main.c, cargo-dist/src/build/generic.rs, cargo-dist/src/host.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/mock.rs
paired with https://github.com/axodotdev/axoproject/pull/136
=> feat: generic workspaces

cargo-dist/src/build/cargo.rs, cargo-dist/src/build/generic.rs, cargo-dist/src/env.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs
Similar to the work that was done in generic builds recently, this passes a working directory to CLI commands that are pwd-sensitive. This specifically covers `cargo`, `git`, and `brew bundle`; I left things like linkage alone, because those don't do anything with the pwd.
=> feat: pipe working directory into more CLI commands

book/src/installers/updater.md
This only covers testing the standalone updater, and provides links to axoupdater's documentation for using it as a crate.
=> docs: document tokens in CI testing

Cargo.lock
Two dependabot PRs that didn't conflict still led to slightly inconsistent dependencies - this commits the lockfile after running `cargo build`.
=> chore: fix deps

axoproject/Cargo.toml
I missed that axoproject's Cargo.toml had a dep version bumped; thought it was cargo-dist's, where we can be less careful about versioning.
=> chore: re-drop url in Cargo.toml

cargo-dist/src/build/generic.rs
Prior to this, generic builds were being passed the manifest_path, which is the path to the *manifest file* - not the directory *containing*  the manifest. This caussed the `current_dir` part of the command to error out during the `chdir` that came before the actual command invocation.
=> fix: pass correct path to generic builds

axoproject/src/lib.rs
The argument was renamed in a7ab04fc5aebe328aafece66adeab94cd32ad5cb, but the documentation wasn't updated to reflect that.
=> docs: fix argument name for get_workspaces

cargo-dist/tests/gallery/command.rs, cargo-dist/tests/gallery/dist.rs, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_generic_workspace_basic.snap
This adds a test running on a generic workspace, specifically covering the mixed-content workspace. Right now, we expect cargo-dist to only cover the generic half and not be able to find the other half.
I duplicated the "patch Cargo.toml" logic because the structure is a bit different and I didn't feel like genericizing the original method at this point.
This doesn't actually work yet: the output indicates that it patched `dist-workspace.toml` with the expected content, but the cargo build acts like it's working on the unpatched file. I'm sure I missed something obvious I'll see in the morning.
=> tests: add generic workspace tests

book/src/installers/npm.md
These existed in another file, but not this one.
=> docs: fix broken links in npm docs

.github/workflows/release.yml, Cargo.lock, Cargo.toml, cargo-dist/Cargo.toml, cargo-dist/src/host.rs, cargo-dist/src/lib.rs, cargo-dist/src/main.rs, cargo-dist/src/net.rs, cargo-dist/src/sign/mod.rs, cargo-dist/src/sign/ssldotcom.rs, cargo-dist/src/tasks.rs
The main goal of this is actually updating axoasset to 1.0.0 and
enabling the tls_native_roots feature as appropriate.
This speculatively also adds a ClientSettings type which isn't really
important but ensures all the places where we make clients are flagged
for future updates.
=> feat: add experimental tls_native_roots feature

cargo-dist/src/config.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/config.rs
This preps us for a future release where we change the default, making it easier for people using the previous default to keep it.
I considered migrating away from `Opt<Vec<_>>`, but this made it easier to keep `opt_string_or_vec`.
Fixes #1194.
=> feat: inline default install-path

cargo-dist/src/errors.rs, cargo-dist/src/host.rs, cargo-dist/src/init.rs, cargo-dist/src/tests/host.rs, cargo-dist/src/tests/mock.rs, cargo-dist/src/tests/mod.rs
In various refactors this code got overly permissive, silently allowing 'no repository url set at all' in cases where it's invalid. Later code would then panic with an obtuse message about it being impossible (because it should be).
=> fix: restore proper diagnostics for repository url

cargo-dist/src/linkage.rs
We had the -msvc triples here, but were missing the -gnu ones.
Fixes #1219.
=> fix: add missing triples to linkage check

Cargo.lock, axoproject/Cargo.toml, axoproject/src/errors.rs, axoproject/src/lib.rs, axoproject/src/local_repo.rs, cargo-dist/src/config.rs, cargo-dist/src/tasks.rs
This captures information about the git repository we're running builds in, including its absolute path on disk and its current git HEAD.
We already used the side effects of capturing this information in the past; this lets us capture and hold on to it.
=> feat: add Repo struct

Cargo.lock, Cargo.toml
Similar to 0.20.0-prerelease.4, except this is made from the 0.20.0 release branch so it doesn't contain extraneous commits that we don't plan to release.
=> release: 0.20.0-prerelease.5

cargo-dist/src/backend/ci/github.rs, cargo-dist/templates/ci/github/release.yml.j2, cargo-dist/tests/snapshots/axolotlsay_build_setup_steps.snap
Objects in templates will already be renamed so `if_expr` will always be `undefined` when outputting templates.
=> Change `if_expr` to `if` in templates

cargo-dist/src/init.rs
If we receive ctrl-c during `init`, dialoguer leaves the cursor hidden and the user may not understand why that's happened. We need to make sure we restore the cursor before terminating the application.
While this may be handled by dialoguer/console at some point, this would make for a nicer user experience today.
=> init: ensure terminal is restored when interrupted

cargo-dist/src/init.rs
Copying the existing `[dist]` element is also bringing its leading whitespace along for the ride, if any. We want to retain any comments that were attached to it, but not empty leading whitespace.
=> fix: handle leading whitespace on [dist] migration

cargo-dist/src/init.rs
If we're not migrating, we shouldn't assume the filename, or we might get confused about whether we're meant to be writing to dist.toml or dist-workspace.toml.
Fixes `cargo dist init` in `dist.toml`-based workspaces.
=> fix: only calculate filename when migrating

Cargo.lock, Cargo.toml
Incorporates the two most recent improvements to `cargo dist init` migration.
=> release: 0.20.0-prerelease.7

book/src/install.md
We say "not NixOS" about a different option earlier, so it's worth mentioning the actual Nix install.
=> docs(install): document nix

cargo-dist/src/cli.rs, cargo-dist/src/init.rs, cargo-dist/src/main.rs
We now opt into the new configuration format via `cargo dist init --opt-in-migrate`. Users who don't pass this flag won't have the new format offered to them. Users with an already-initted project will be asked if they want to opt in, while users with a Cargo.toml project will be automatically given the new format.
(Best viewed with `?w=1`)
=> feat: guard new config format behind hidden flag

book/src/ci/customizing.md
Although we indirectly documented this later in the page, we didn't properly document this in the place it's most relevant.
Closes #1244.
=> docs: document native runner for arm64 libraries

CHANGELOG.md
This is missing the new workspace configuration; @Gankra's writing that part. That section is meant to come before the new configuration section, which is why that doesn't explain what the new config format is.
=> docs: changelog for 0.20.0

book/book.toml
This works again as of oranda 0.6.5.
=> docs: restore linkcheck

CHANGELOG.md, Cargo.lock, Cargo.toml
Ensures our release number is up to date, and brings in the changelog.
=> chore: backport releases

cargo-dist/templates/installer/npm/npm-shrinkwrap.json, cargo-dist/templates/installer/npm/package.json, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_alias.snap, cargo-dist/tests/snapshots/axolotlsay_alias_ignores_missing_bins.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap, cargo-dist/tests/snapshots/axolotlsay_build_setup_steps.snap, cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_several_aliases.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
Backported copy of #1274 for the 0.20.x series branch.
Bumps [axios](https://github.com/axios/axios) from 1.7.2 to 1.7.3.
- [Release notes](https://github.com/axios/axios/releases)
- [Changelog](https://github.com/axios/axios/blob/v1.x/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v1.7.2...v1.7.3)
---
updated-dependencies:
- dependency-name: axios dependency-type: direct:production update-type: version-update:semver-patch ...
=> chore(deps): bump axios in /cargo-dist/templates/installer/npm

cargo-dist/src/init.rs, cargo-dist/src/tests/config.rs
e.g., the following is incorrect https://github.com/axodotdev/cargo-dist/blob/39abb63c095a8bf9559bf45ab339cf821d15148d/Cargo.toml#L88-L89
=> Fix generated comment describing `pr-run-mode`

Cargo.lock, Cargo.toml, axoproject/src/errors.rs, axoproject/src/generic.rs, axoproject/src/javascript.rs, axoproject/src/lib.rs, axoproject/src/repo.rs, axoproject/src/rust.rs, cargo-dist/src/config.rs, cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/mock.rs, cargo-dist/tests/gallery/dist.rs
Use the [dist] section package dist.tomls, and add errors for cases where a metadata.dist exists but is being ignored.
Also handles npm package scopes better.
Also handles url equality checks better.
fixes #1308 
fixes #1307
=> fix: javascript workspace bugs

Cargo.lock, Cargo.toml, axoproject/src/lib.rs, cargo-dist/src/announce.rs
Every user of this was removed except for a use in the --tag=timestamp path, which meant that adding a javascript/generic project to it would needlessly panic and crash without actually checking if the version was semver compatible
=> fix: remove last vestiges of version::cargo

book/book.toml
These pages were deleted/moved in the recent docs rewrite. While they were less popular than the previous one we've redirected, it's still worth adding redirects to new homes for them just in case any links or search results were pointing to them.
=> docs: add two more redirects

book/book.toml
when i originally made this redirect i was focused on doing a best-effort match to the previous content. however, i didn't realize the quickstart was showing up for generic "cargo-dist" searches (see below, makes a lot of sense). i think putting the redirect at the index page makes more sense here. we *may* want to soup up that page so it's a little nicer than it is currently, but i think the best redirect goes to the index, souped up or not :)
=> fix(redirect): quickstart -> quickstart index

cargo-dist/src/env.rs
The `brew bundle exec -- /usr/bin/env` output now contains multiline strings, which I should always have been guarding against anyway. This updates us to use the `-0` option to `env`, which separates lines in the output by nul bytes instead of newlines - that way we can more safely parse the output of environment variables containing newlines.
=> fix: parsing multiline brew output

cargo-dist/src/backend/installer/homebrew.rs
These two tests produce different results in Homebrew's SPDX parser, but that appears to be a bug in Homebrew's parser rather than this one. Added notes to both tests so that we expect the results to be different from what Homebrew returns.
refs https://github.com/axodotdev/cargo-dist/pull/1345#discussion_r1723932405.
cc @cxreiff
=> docs: add notes to two SPDX tests

cargo-dist/src/errors.rs, cargo-dist/src/linkage.rs
* Windows staticlibs are `ar` archives, not PE executables. Make sure we handle those in the Windows object parsing case.
* Make unsupported binary checks nonfatal. In this case we can simply return a default instead of failing the build.
* Provide the filename in the LinkageCheckUnsupportedBinary error, making it more informative in the cases it does end up getting printed.
Fixes #1356.
=> feat: improve staticlib handling, errors

cargo-dist/src/errors.rs
This error message ended up surviving the field rename.
=> fix: error message references old config name

Cargo.lock, Cargo.toml, cargo-dist/Cargo.toml, cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config.rs, cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/sign/macos.rs, cargo-dist/src/sign/mod.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/ci/github/release.yml.j2
This adds support for codesigning on macOS, similar to the ssl.com feature on Windows. In the current revision, we only perform signing with a certificate - notarization will come in a subsequent feature.
As with ssl.com, the only feature in our config is the feature controlling whether or not to sign - the rest is handled via the environment/Actions secrets. The user needs to provide three fields:
* A pkcs12 certificate, base64-encoded.
* The passphrase for that certificate.
* The name of the codesigning identity belonging to that certificate.
If all three are present, we'll codesign any binaries and libraries during the local build process.
This uses the builtin macOS tooling, which means it can only be performed on a macOS host. (That's not too different from how we can only do the …
=> feat: macOS codesigning

.github/workflows/release.yml, Cargo.lock, Cargo.toml
The previous release went out as 0.22.0, but we're currently targeting 0.21.2. The diff from the 0.22.0 release: https://github.com/axodotdev/cargo-dist/compare/v0.21.1..v0.22.0-prerelease.1
0.22.0-prerelease.1 contains SPDX and `brew style`, which are also contained in this prerelease.
=> release: 0.21.2-prerelease.1

Cargo.lock, Cargo.toml
Dep tree size grew slightly because we also depend directly on an older homedir.
=> chore(deps): axoupdater 0.7.1

Cargo.lock, Cargo.toml, cargo-dist/Cargo.toml
We rewrote the test in cee08da9f4044a50bc0feec644c06236e35fde91, which removed the one usage of the homedir dev-dependency.
=> chore(deps): remove unused dep

cargo-dist/src/build/mod.rs, cargo-dist/src/errors.rs, cargo-dist/src/linkage.rs
=> fix: make linkage truly infallible

cargo-dist/src/backend/installer/macpkg.rs, cargo-dist/src/backend/installer/mod.rs, cargo-dist/src/config.rs, cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/manifest.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_alias.snap, cargo-dist/tests/snapshots/axolotlsay_alias_ignores_missing_bins.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap, cargo-dist/tests/snapshots/axolotlsay_build_setup_steps.snap, cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap, cargo-dist/tests/snapshots/axolotlsay_several_aliases.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign.snap, cargo-dist/tests/snapshots/axolotlsay_ssldotcom_windows_sign_prod.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap
This adds support for building Mac .pkg installers. This current implementation is intentionally a bit simplistic: it produces one .pkg per package in the user's workspace, without any special branding applied. We currently only allow the app identifier and install location to be configured, but we can consider adding further customization in the future.
Although I added support for configuring this in `init`, I ran into a bit of trouble serializing that value since the new config is set up as a struct rather than two separate fields.
Here's sample config from one app:
```toml
[workspace.metadata.dist.mac-pkg-config]
identifier = "dev.axo.cargo-dist"
install-location = "/usr/local"
```
And here's the No Name / Sans nom installer it produces:
=> feat: Mac .pkg installer

book/src/ci/customizing.md
I believe the minimum version was bumped by https://github.com/axodotdev/cargo-dist/pull/1285. This pull request reflect the change to the document.
=> Update customizing.md about the version of macOS runners

Cargo.lock, Cargo.toml
This contains a bugfix for `cargo dist selfupdate` which would occur if the install receipt pointed to an installation directory that doesn't exist.
=> chore(deps): axoupdater 0.7.2

cargo-dist/src/cli.rs, cargo-dist/src/init.rs, cargo-dist/tests/snapshots/markdown-help.snap
* Publicizes the `--opt-in-migrate` flag, which was previously hidden.
* Leaves package-specific config alone in `[package.metadata.dist]`.
Fixes #1405.
=> feat: enable public migration

cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs
If the user supplies an npm scope with invalid characters, we should error out instead of accepting it. Accepting it means it will error out during publish instead.
Fixes #994.
=> feat: return an error for an invalid scope

book/src/installers/npm.md, cargo-dist/src/errors.rs, cargo-dist/src/init.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/installer/npm/binary-install.js, cargo-dist/templates/installer/npm/binary.js, cargo-dist/templates/installer/npm/npm-shrinkwrap.json, cargo-dist/templates/installer/npm/package.json, cargo-dist/tests/snapshots/axolotlsay_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_alias.snap, cargo-dist/tests/snapshots/axolotlsay_alias_ignores_missing_bins.snap, cargo-dist/tests/snapshots/axolotlsay_basic.snap, cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap, cargo-dist/tests/snapshots/axolotlsay_build_setup_steps.snap, cargo-dist/tests/snapshots/axolotlsay_disable_source_tarball.snap, cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap, cargo-dist/tests/snapshots/axolotlsay_several_aliases.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap, cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
This removes the node tar library, and instead commits to unzipping/untarring files the same way that we do in the shell and powershell installers.
Fixes #226.
This isn't tested yet; opening a PR to make sure I'm not completely off base in the JS-side formatting/logic.
=> feat: support any format in npm

cargo-dist/src/cli.rs, cargo-dist/src/init.rs, cargo-dist/src/main.rs, cargo-dist/tests/snapshots/markdown-help.snap
Based on a conversation with @ashleygwilliams, a few changes to the new config format stuff in `cargo dist init`.
* Removes the `--opt-in-migrate` flag
* New projects always get the new config
* Existing projects are offered the chance to migrate, with the default being no
* Existing projects using `cargo dist init -y` don't get migrated
=> feat: adjust new config opt-in

axoproject/src/generic.rs, axoproject/src/javascript.rs, axoproject/src/lib.rs, axoproject/src/rust.rs, axoproject/src/tests.rs, book/src/installers/updater.md, cargo-dist/src/build/cargo.rs, cargo-dist/src/errors.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/src/tests/mock.rs
This adds a check when building Rust software which uses axoupdater as a library. If the user is using a version older than what this version of cargo-dist was for, it emits a warning at buildtime. I tested it on cargo-dist itself by bumping the const to something that doesn't exist, and confirmed it works:
```
WARN Your project uses axoupdater as a library. We've detected that you're using 0.7.2, but this version of cargo-dist expects a version of at least 0.10.0 (or greater). Please consider updating to ensure your users don't experience inconsistent update behaviour.
```
To support this, I added support in axoproject for detecting if axoupdater is present and, if it is, its version is recorded. I briefly considered tracking the full dep tree in the axoproject info but that seemed like …
=> feat: add minimum supported axoupdater check (library)

book/src/installers/updater.md, cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap
This was broken in a refactor in 19af85324be25d023b2bac291aa105f081d7da30. That commit updated how we fetch platform-specific information, but it missed that the `updater` field in the new type is differently-shaped than the field from the new type. Specifically, the new `archive` we're working on has an `updater` field that's an *index into a table of updaters* intead of an *updater struct* - so trying to read its `id` and `bin` fields was doomed to failure.
The snapshots in #1346 actually exposed this problem, but both Aria and I missed it in review. We need to be more careful about this in the future.
Fixes #1443.
=> fix: standalone updater installation

cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/snapshots/akaikatana_updaters.snap, cargo-dist/tests/snapshots/axolotlsay_updaters.snap
Because minijinja's syntax derives from Python, it's also inherited Python's semantics for falsiness. `0` is falsy and, in this context, so is `Some(0)`. The result is that `if archive.updater` wasn't just checking for definedness but for truthiness, and it would be false for the updater with index `0`.
Fixes #1450.
=> fix: invalid updater for first in array

cargo-dist/src/backend/installer/msi.rs
To avoid an error when generating a wix file for a package whose Cargo.toml is in a sub-folder, specify the full path to the package's Cargo.toml.
Fixes Issue #1453.
=> Specify path to Cargo.toml when generating wix for package

axoproject/src/local_repo.rs, cargo-dist/src/backend/ci/github.rs
Prior to this, our path handling for Windows produced some slightly chaotic paths - they would begin and end with Unix-style line endings, but would have one native Windows line ending in the middle. This fixes that: we now normalize the path we get from `git`, and assign the constant with the hardcoded file separator appropriately on Windows.
Note that this never affected the behaviour of anything; this was always just a display bug.
Before:
```
generated Github CI to C:/Users/misty/inittest\.github/workflows/release.yml
```
After:
```
generated Github CI to C:\Users\misty\inittest\.github\workflows\release.yml
```
Fixes #1456.
=> fix: print Windows paths correctly

Cargo.lock
This version updates nix to the latest:
https://github.com/ljtpetersen/homedir/blob/v0.3.4/CHANGELOG.md
Closes #1466.
=> chore(deps): homedir 0.3.4

axoproject/src/rust.rs
=> Distinguish "cargo metadata failed" from "cargo is not installed"

cargo-dist-schema/Cargo.toml
We don't run any of these; 17 lines just saying "ignored" is distracting from the test content we actually care about. eg
```
Doc-tests cargo_dist_schema
running 17 tests
test cargo-dist-schema/src/macros.rs - macros::declare_strongly_typed_string (line 110) ... ignored
test cargo-dist-schema/src/macros.rs - macros::declare_strongly_typed_string (line 12) ... ignored
test cargo-dist-schema/src/macros.rs - macros::declare_strongly_typed_string (line 126) ... ignored
test cargo-dist-schema/src/macros.rs - macros::declare_strongly_typed_string (line 138) ... ignored
test cargo-dist-schema/src/macros.rs - macros::declare_strongly_typed_string (line 155) ... ignored
test cargo-dist-schema/src/macros.rs - macros::declare_strongly_typed_string (line 170) ... ignored
test …
```
=> tests: disable cargo-dist-schema doctests

.gitattributes
See https://github.com/github-linguist/linguist/blob/main/docs/overrides.md
When looking at a PR like https://github.com/axodotdev/cargo-dist/pull/1503/files there's a _lot_ of scrolling involved just for .snap files —  sure we probably should open up a couple and check what's in there, but having 60+ of them opened by default just makes the GitHub UI sluggish and makes the review experience poorer.
=> Have snapshots files be collapsed in GitHub by default

Cargo.toml
This has been extracted out of https://github.com/axodotdev/cargo-dist/pull/1470 and it's part of making a faster "edit-compile-test-in-ci" cycle when working on cross-compilation.
The rationale is included as inline comments.
=> Tune the 'dev' profile

Cargo.lock, Cargo.toml
This pulls in the environment variables to override compression level, which enables faster iteration. cf. https://github.com/axodotdev/axoasset/pull/212
=> Upgrade to axoasset 1.0.1

.github/workflows/ci.yml
The `rust-cache` action uses environment variables as part of the cache key:
```
env-vars: ""
```
Since the per-run `GITHUB_TOKEN` was being placed in the `CARGO_DIST_GITHUB_TOKEN` variable (which matches the defaults above), each test run had a unique cache key and every cache lookup in CI was a cache miss. Downloading and compiling on Windows (as an example) takes >8m with no cache so this should provide a dramatic speed-up.
I tested this by pushing an empty commit to the branch and observed that the cache key was unchanged. If you want, I can push another empty commit here to demonstrate the fix and speed-up, but it looks like you don't squash merge so I shall not by default.
=> Fix cache misses in CI tests

.github/workflows/release.yml, Cargo.lock, Cargo.toml, cargo-dist/tests/snapshots/manifest.snap, dist-workspace.toml
This updates to the new prerelease and configures us to cross-compile to aarch64-linux instead of using Buildjet runners. It also sets the PR build mode to "upload" so we can see if it works.
=> Update own dist and test cross-compiling

cargo-dist/src/backend/installer/msi.rs
Use an explicit manifest path when building MSI with WiX, in case Cargo.toml is in a sub-folder.
Unfortunately I missed this in https://github.com/axodotdev/cargo-dist/pull/1454.
=> Explicitly set manifest path when building MSI with WiX

book/src/reference/config.md
- correct name of `omnibor` setting
- link to omnibor website
- rephrase omnibor setting explanation
- add example usage for the `omnibor`, `cargo-auditable`, and `cargo-cyclonedx` settings
- remove unnecessary escape characters in `min-glibc-version` documentation
=> Documentation cleanup

cargo-dist/src/announce.rs, cargo-dist/tests/gallery/dist.rs, cargo-dist/tests/integration-tests.rs
In the past, we'd ignore `dist=false` when trying to enable single-package/library mode. This is, frankly, quite confusing and not desirable. Even if it's a slightly backwards incompatible change, we should make this do what it actually says.
Fixes #1287.
=> feat: disable single-library mode for dist=false

cargo-dist/src/init.rs
I picked `false` as the default when `--yes` is passed, since that's also the default for keymashing enter.
Best viewed with `?w=1`.
Fixes #1610.
=> fix: provide default for install updater question

cargo-dist/src/backend/installer/msi.rs, cargo-dist/src/config/mod.rs, cargo-dist/src/init.rs
Neither of them are Cargo.toml-specific in any way.
=> Rename save_cargo_toml()->write_toml() and load_cargo_toml()->load_toml().

cargo-dist/src/errors.rs, cargo-dist/src/lib.rs
This was never all that reliable, and it's become less reliable since shipping cross compilation. It's also not really used: we provide binaries for all of the common release targets. We can consider restoring a more functional version in the future, but for now we should turn it off.
=> feat: disable axoupdater-from-source

Cargo.toml
The guppy we use says it's for Rust 1.73, so that's our actual MSRV.
=> chore: tweak rust-version

cargo-dist/src/build/cargo.rs
In testing, I've been able to confirm that cargo-auditable and cargo-xwin are compatible; zigbuild is the only one with a compatibility issue.
Refs #1608.
=> feat: enable auditable with xwin

cargo-dist/src/cli.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/main.rs, cargo-dist/tests/snapshots/long-help.snap, cargo-dist/tests/snapshots/markdown-help.snap, cargo-dist/tests/snapshots/short-help.snap
- `dist init` still works as on main
- `dist migrate` does the migration part of `dist init`
- `dist init`'s migration functionality is now implemented in terms of `dist migrate`
This shows `dist migrate` on its own:
And this shows that `dist migrate` is _only_ a migration, and explicitly does not do the re-init part:
=> Refactor `dist init` and split out `dist migrate`

book/src/artifacts/archives.md, book/src/reference/concepts.md
We have several references to cross-compile not existing; these should just be removed, so users searching for cross-compiles in the docs will find the actual instructions for the new feature.
=> docs: clean up old cross-compile references

cargo-dist/src/build/generic.rs, cargo-dist/src/errors.rs, cargo-dist/src/tasks.rs
These options aren't valid when performing generic builds, and we should give the user a warning about that as far ahead of time as we can. Output during `plan`:
```
× You're building a generic package but have a Cargo-only option enabled
help: Please disable the following from your configuration: cargo-auditable, cargo-cyclonedx
```
I've confirmed that there are no errors during Rust builds.
Fixes #1526.
=> feat(generic): error on using cargo-only options

Cargo.lock, Cargo.toml
Branched from main, so this has the same content as #1607.
=> release: 0.26.0-prerelease.4

CHANGELOG.md, Cargo.lock, Cargo.toml, cargo-dist/src/backend/ci/github.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_cross2.snap
This is a bugfix release branched off of 99c10d2ba1e5a0aaaa481d019a252121cad2c767 which contains #1635 and no other new content.
=> release: 0.26.1

cargo-dist/src/init.rs
Previously we'd leave this in the public jobs and we'd leave the npm scope despite the fact that the user requested us to turn off the npm installer.
=> fix: remove npm from publish-jobs when disabled

Cargo.lock, Cargo.toml, cargo-dist/src/config/v0.rs, cargo-dist/src/config/v0_to_v1.rs, cargo-dist/src/config/v1/installers/mod.rs, cargo-dist/src/init.rs, cargo-dist/src/lib.rs, cargo-dist/src/tasks.rs, cargo-dist/tests/integration-tests.rs
Instead of always fetching the latest axoupdater, fetch the version that this version of dist itself uses as a library. That way, we're always fetching something predictable.
=> feat: update axoupdater, fetch known-good version

cargo-dist/src/lib.rs
I've also adjusted what counts as a "global" build - the "all" and "host" modes build global artifacts too, so we should check those.
We discussed this and realized there was a mismatch between how we check for cyclonedx and how we use it. It's currently executed in CI, rather than from Rust as one of the builds, so we don't actually run it during `cargo build -aglobal`. As a result there's no real reason to check for it right now - it's always installed in the only place we use it. We can add back the check if we move the execution to Rust. #1652
=> fix: cyclonedx check is unnecessary (only called in CI)

axoproject/src/generic.rs, cargo-dist/src/init.rs
We treat dist.toml-alone generic projects a bit awkwardly because of our migration to the new metadata structure. The easiest solution for us is to migrate those proejcts to dist-workspace.toml, where they can be structured and interpreted the same as Cargo.toml projects with a dist-workspace.toml file.
~~Currently, this produces a pair of `dist-workspace.toml` and `dist.toml`. The `dist.toml` retains the package-level metadata, while the `dist-workspace.toml` contains a workspace entry with a single `dist:.` member and the `[dist]` metadata.~~
At @ashleygwilliams's suggestion, I've updated axoproject so it now supports generic projects whose `dist-workspace.toml` contains a `[workspace]` and `[package]` in the same file, and we produce that single metadata when migrating …
=> feat: migrate dist.toml to dist-workspace.toml

.github/workflows/release.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, dist-workspace.toml
This is a draft until we finish merging all of this release's content.
=> release: 0.27.0

cargo-dist/src/init.rs
A condition like the following was intended to be switched from `==` to `!=`:
A == B && C == D
The correct way to do this would be:
A != B || C != D
However, instead, what we had was this inverted logic:
A != B && C != D
In practice, because of the specific things we were checking, this meant instead of *never* deleting dist-workspace.toml, we were *always* deleting it.
=> fix: Avoid 'dist migrate' deleting dist-workspace.toml.

cargo-dist/src/errors.rs, cargo-dist/src/tasks.rs, cargo-dist/templates/installer/installer.ps1.j2, cargo-dist/templates/installer/installer.sh.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_abyss.snap
Previously, if the user was multi-host drifting, we preferred to install from Axo. This swaps it so we now prefer GitHub.
We also now make Axo-only publishing an error; GitHub-only and GitHub+Axo are both valid.
=> feat: prioritize github over axo

cargo-dist/src/backend/ci/github.rs, cargo-dist/tests/snapshots/axolotlsay_cross2.snap
The default xwin cross-compile container is apt-based; we should allow apt packages to be installed here without extra configuration on the user's part.
Fixes #1670.
=> fix: allow installing apt packages in xwin

cargo-dist-schema/src/snapshots/cargo_dist_schema__emit.snap, cargo-dist/tests/snapshots/akaikatana_musl.snap, cargo-dist/tests/snapshots/axolotlsay_checksum_blake2b.snap, cargo-dist/tests/snapshots/axolotlsay_checksum_blake2s.snap, cargo-dist/tests/snapshots/axolotlsay_checksum_sha3_256.snap, cargo-dist/tests/snapshots/axolotlsay_checksum_sha3_512.snap, cargo-dist/tests/snapshots/axolotlsay_custom_formula.snap, cargo-dist/tests/snapshots/axolotlsay_custom_github_runners.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss.snap, cargo-dist/tests/snapshots/axolotlsay_dispatch_abyss_only.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_linux_only.snap, cargo-dist/tests/snapshots/axolotlsay_homebrew_macos_x86_64_only.snap, cargo-dist/tests/snapshots/axolotlsay_musl.snap, cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap, cargo-dist/tests/snapshots/axolotlsay_no_locals.snap, cargo-dist/tests/snapshots/axolotlsay_no_locals_but_custom.snap, cargo-dist/tests/snapshots/axolotlsay_tag_namespace.snap, cargo-dist/tests/snapshots/error_manifest.snap, cargo-dist/tests/snapshots/long-help.snap, cargo-dist/tests/snapshots/markdown-help.snap, cargo-dist/tests/snapshots/short-help.snap
cargo-insta 1.42.0 reverted a change made to the snapshot format in a previous version. Our snapshots are a mix of the two formats; this PR updates them all to the 1.42.0/pre-1.41.0 format for consistency.
=> chore: update snapshots to new format

book/src/reference/config.md
The option is actually called `install-success-msg`; using `custom-success-msg` does not work.
Unrelated thing I noticed while testing this option: Backticks inside that message actually behave as shell backticks. Not sure if intentional or not (can't think of any reason why someone would want this). Maybe that deserves a warning so people are not surprised by it, or to be fixed so the message can contain anything w/o being interpreted by the shell?
=> docs: Fix incorrect option name

cargo-dist/src/config/mod.rs, cargo-dist/src/config/v1/artifacts/mod.rs, cargo-dist/src/config/v1/installers/mod.rs
This is needed for implementing the v0->v1 config migration.
=> (config-migration) Implement `Display` for `ChecksumStyle`, derive `Default` for `ArtifactLayer` and `InstallerLayer`

cargo-dist/src/config/v1/layer.rs
These functions are needed for implementing the v0->v1 config migration.
=> (config-migration) Add BoolOr<T> and Option<BoolOr<T>> helper functions.

cargo-dist/tests/snapshots/axolotlsay_generic_workspace_basic.snap
This smells like a semantic merge conflict, but I'm not sure how it happened.
=> Regenerate a test snapshot

.github/workflows/ci.yml, cargo-dist/src/backend/ci/mod.rs
They release multiple things from one repo, so latest isn't always omnibor-cli.
I discovered this before (hence the note in `backend/ci/mod.rs`), but forgot to treat `ci.yml` the same way.
=> Pin omnibor-cli version for CI workflow

book/src/ci/customizing.md
This makes a couple of changes to the `github-build-setup` recommendations:
* Recommends the user place their custom build setup file outside `.github/workflows` to avoid GitHub mistaking it for a second workflow.
* Uses the `dist-workspace.toml` table name instead of the deprecated `Cargo.toml` one.
refs #872.
closes #1750.
=> docs: update build-setup recommendations

axoproject/src/generic.rs, cargo-dist/src/config/v1/mod.rs, cargo-dist/src/config/version.rs, cargo-dist/src/errors.rs, cargo-dist/src/migrate/from_v0.rs
<details>
<summary>starting Cargo.toml</summary>
```toml
[package]
name = "axolotlsay"
description = "💬 a CLI for learning to distribute CLIs in rust"
version = "0.2.275"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mistydemeo/cargodisttest.git"
homepage = "https://github.com/mistydemeo/cargodisttest"
[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
unicode-width = "0.1.10"
[dev-dependencies]
assert_cmd = "2.0.8"
[workspace.metadata.dist]
cargo-dist-version = "0.25.1"
ci = "github"
installers = ["shell", "powershell"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
pr-run-mode = "plan"
hosting = "github"
install-updater = true
#github-attestations = true
install-path = …
```
=> (config-migration) Add `do_migrate_from_v0()` implementation

cargo-dist/tests/snapshots/manifest.snap, dist-workspace.toml
Until we have a new release created that defaults to this version.
=> ci: use ubuntu-22.04 for x86_64 linux builds

book/src/installers/usage.md
Cherry-picked from https://github.com/astral-sh/cargo-dist/pull/32.
=> Fix typo for installer base url override

.github/workflows/ci.yml
Since active work is happening on here in addition to main right now.
=> ci: run for stable branch

cargo-dist/templates/ci/github/release.yml.j2, cargo-dist/tests/snapshots/axolotlsay_abyss.snap
Backported to the stable branch from #1702.
=> update version of github provenance action

Cargo.lock, Cargo.toml
Same content as 0.28.1-prerelease.1, but built using that version instead of an older cargo-dist.
=> release: 0.28.1-prerelease.2

.github/workflows/web.yml
I'm planning to get back to the 1.0 branch later and get that released, but since the next couple of releases will be coming from the pre-1.0 branch, the public docs should reflect that.
=> ci: publish docs from stable

cargo-dist/src/main.rs, cargo-dist/tests/cli-tests.rs
This reverts commit c613fc81d959064c46bd884a0c548ee1ee0329ea.
This was added at the time we expected that release to be the final pre-1.0 release. Since I'm releasing an 0.28.1, that's not the right time to do a full rename; we should release 0.28.1 under the old name and go ahead with the rename at a later point in time.
=> Revert "feat: add rename infrastructure"

.github/dependabot.yml
For the time being, we'll be maintaining two branches. This can be removed once the last bits of 1.0 are ready to go.
=> deps: run dependabot on stable too

cargo-dist/tests/cli-tests.rs
This should be safe now that 0.28.1 is out.
=> tests: reenable self-updater test

cargo-dist/tests/cli-tests.rs
This is hitting rate limits from the GitHub API constantly. I don't remember it being this bad before! Just turn it off for now, but look into maybe authing with the actions token or something else to get a higher limit for more reliable tests.
=> tests: re-disable self updater test

axoproject/src/lib.rs
Backports #1978 to the 0.x branch.
=> fix(axoproject): allow building without generic-projects

book/src/ci/customizing.md, book/src/installers/usage.md, book/src/reference/concepts.md, book/src/reference/config.md
These originated in the Astral fork but didn't get docs there, so I wrote these from scratch.
=> docs: add docs for 0.29.0 features

cargo-dist/src/tasks/mod.rs
This PR enables cross-compilation from windows to windows. This is needed to compile `aarch64-pc-windows-msvc` targets from another windows machine which is generally supported. This change was discussed in https://github.com/axodotdev/cargo-dist/issues/1644 but never materialized in a PR.
Fixes https://github.com/axodotdev/cargo-dist/issues/1644
=> fix: allow cross compiling from windows to windows

cargo-dist/oranda.json
Removes references to the axo.dev domain from the Oranda config.
=> chore(oranda): remove outdated domain refs

cargo-dist/src/backend/ci/github.rs, cargo-dist/tests/snapshots/axolotlsay_cross1.snap
GitHub now provides Linux ARM64 hosted runners for free in public repositories. This change updates the default runner for aarch64-unknown-linux-gnu targets to use ubuntu-22.04-arm instead of the x86_64 runner.
See: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Addresses https://github.com/axodotdev/cargo-dist/issues/74
=> use GitHub ARM-specific runners for aarch64 Linux targets by default

CHANGELOG.md, book/src/reference/config.md, book/src/supplychain-security/attestations/github.md, cargo-dist-schema/src/lib.rs, cargo-dist-schema/src/snapshots/dist_schema__emit.snap, cargo-dist/src/backend/ci/github.rs, cargo-dist/src/config/mod.rs, cargo-dist/src/config/v0.rs, cargo-dist/src/config/v0_to_v1.rs, cargo-dist/src/config/v1/hosts/github.rs, cargo-dist/src/init/v0.rs, cargo-dist/src/manifest.rs, cargo-dist/src/tasks/mod.rs, cargo-dist/templates/ci/github/partials/publish_github.yml.j2, cargo-dist/templates/ci/github/release.yml.j2, cargo-dist/tests/integration-tests.rs, cargo-dist/tests/snapshots/axolotlsay_attestations_filters.snap, cargo-dist/tests/snapshots/axolotlsay_attestations_host.snap
Closes https://github.com/axodotdev/cargo-dist/issues/1754
Two integration tests were added to confirm functionality behaves as expected.
Originally opened in https://github.com/astral-sh/cargo-dist/pull/45
=> Add support for attestations in the host phase

cargo-dist/src/platform.rs
The architecture's name is better spelled as "LoongArch" in documents, instead of "LOONGARCH" which looks like an identifier.
=> feat: use canonical TitleCase for LoongArch64 Linux targets
